### PR TITLE
fix(core): import common package correctly

### PR DESCRIPTION
**Pull request by meteorlxy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Using relative path import will fail in pnpm workspace

```
Error: Cannot find module '../../common/utils/random-string-generator.util'
Require stack:
- /path/to/project/node_modules/.pnpm/@nestjs+core@9.3.1/node_modules/@nestjs/core/inspector/uuid-factory.js
- /path/to/project/node_modules/.pnpm/@nestjs+core@9.3.1/node_modules/@nestjs/core/injector/instance-wrapper.js
```

## What is the new behavior?

No errors

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by meteorlxy** [comment]
It's kind of a critical issue. Hope we could have a patch release asap.

**Comment by kamilmysliwiec** [comment]
I'll publish a new release very shortly (today)

**Pull request merged**
