### PR TITLE
feat(core,common,platform-fastify): add webdav http methods support

### PR DESCRIPTION
**Pull request by johaven**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
Closes https://github.com/nestjs/nest/issues/9459
Old PR: https://github.com/nestjs/nest/pull/13164

## What is the new behavior?
add new decorators for webdav methods, like @PropFind

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Status
Everything works on both platforms (express, fastify)

### CODE REVIEW

**Comment by johaven** [comment]
According to my tests everything works on my side on both platforms (fastify/express)

@kamilmysliwiec Does that sound good to you ?

**Comment by johaven** [comment]
@kamilmysliwiec Further to this discussion: https://github.com/fastify/fastify/issues/5412, would there be any problems or conflicts using HTTP methods from `fastify.route` rather than from the instance itself?

**Comment by johaven** [comment]
webdav methods that require body and content type analysis are now well implemented in fastify version 4.27.0 (https://github.com/fastify/fastify/pull/5411)

**Comment by johaven** [comment]
Looks good for me

**Comment by johaven** [comment]
@kamilmysliwiec @jmcdo29, is there anything blocking or breaking regarding the integration of these methods ?

**Review by rubiin — APPROVED** [review]

**Pull request merged**
