### PR TITLE
Refactor/enable strict mode

### PR DESCRIPTION
**Pull request by jbpionnier**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by marcus-sa** [comment]
Why turn the `else if` statement into an `if`? That just makes the code look uglier.

**Comment by jbpionnier** [comment]
I wanted to respect the no-else rule
https://williamdurand.fr/2013/06/03/object-calisthenics/
"the code look uglier"... it's subjective

it was just a proposal

**Comment by marcus-sa** [comment]
Never heard about the `no-else rule` before now, so just because a single person creates his own code style in another language (that nobody uses as a standard), that means it should be applied to this?
Sorry man, but that's a totally no-go.


Sure, I might've been too harsh, but that's just the truth :)

**Comment by jbpionnier** [comment]
ok... why not.
i fixed it :-)

**Pull request merged**
