### PR TITLE
feat(@nestjs/core): support `useExisting` provider #2415

### PR DESCRIPTION
**Pull request by underfin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 2415

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by underfin** [comment]
#2262

**Comment by kamilmysliwiec** [comment]
Thanks! Would you be interested in creating a PR to the docs as well? https://docs.nestjs.com/fundamentals/custom-providers

**Comment by underfin** [comment]
OK. nestjs/docs.nestjs.com#447

**Comment by kamilmysliwiec** [comment]
@underfin could you resolve conflicts? I have recently updated interfaces (removed duplicated types for providers). :)

**Comment by underfin** [comment]
I already resolved conflicts.

**Comment by kamilmysliwiec** [comment]
Thanks!

**Pull request merged**
