### PR TITLE
feat(common): route schema for fastify validation / docs

### PR DESCRIPTION
**Pull request by Hexenon**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by Hexenon** [comment]
added docs for validation: https://github.com/nestjs/docs.nestjs.com/pull/548

**Comment by kamilmysliwiec** [comment]
This feature is fastify-related and doesn't make too much sense in case of Nest applications. (`@nestjs/swagger` + `ValidationPipe`)

**Comment by Hexenon** [comment]
Yeah indeed, we know there's a way to do it vía @nestjs/swagger and ValidationPipe, but still there are a lot of implications of migrating a current json-schema source of truth applications. Thats why i created this. With this we can take advantage of the whole json-schema power.

**Comment by webdevlasse** [comment]
we are trying to use json schema and nest together but are running into issues since nest has its own approach.  Both nest and json schema are widely adopted and have good support in the javascript community. do you have a better option for us to use both in our project. of course we can create our own fork, but we think there is a good case for nest supporting json schema and likely there are others in the community in need of this too.

**Comment by kamilmysliwiec** [comment]
The problem here is that we're trying to remain platform-agnostic so the library used to handle HTTP request-response flow has to be considered as an implementation detail. If we introduce a schema decorator, we'd have to add more fastify-specific code to the core which pretty much breaks the primary rule ("agnosticism").

**Comment by kamilmysliwiec** [comment]
I have to close this PR due to the reason I've posted above :(

**Pull request closed without merging**
