### PR TITLE
enhancement(core) exclude routes parameter added for "setGlobalPrefix"

### PR DESCRIPTION
**Pull request by kgrvr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

https://github.com/nestjs/nest/issues/963
Issue Number: 963

## What is the new behavior?
Can exclude routes for setGlobalPrefix method

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Is this possible to get rid of code style changes? This PR has almost 100 files affected now, even though that this particular functionality is being implemented within only a few of them.

**Comment by kgrvr** [comment]
I can try cherry-picking my commits to a new updated branch, but then I've to create a new PR.

**Comment by kamilmysliwiec** [comment]
That would be far better @kgrvr :)

**Comment by kgrvr** [comment]
@kamilmysliwiec 
As decided, I've created a new PR: #1542 by cherry-picking my original commit to a new branch. Please verify. Thanks 👍

**Pull request closed without merging**
