### PR TITLE
feat: @Render() support for fastify-pug

### PR DESCRIPTION
**Pull request by patrickmichalina**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
`TypeError: reply.render is not a function` when using `@Render()` with `fastify-pug`

## What is the new behavior?
`fastify-pug` to work with `@Render()` decorator

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by patrickmichalina** [comment]
Another option would be to define the view function name to be configured ahead of time instead of performing the check each function call.

**Comment by kamilmysliwiec** [comment]
Out of curiosity, do you know why `fastify-pug` doesn't use `.view()` (as "other" rendering engines for fastify)?

**Comment by patrickmichalina** [comment]
@kamilmysliwiec I do not.

I guess it would be better to change this here: https://github.com/SerayaEryn/fastify-pug/blob/master/index.js#L10

What do you think?

**Comment by patrickmichalina** [comment]
I added this: https://github.com/SerayaEryn/fastify-pug/pull/38 and hoping can fix it there.

**Pull request closed without merging**
