### PR TITLE
feat: add custom printer to built-in logger

### PR DESCRIPTION
**Pull request by ianzone**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

https://github.com/nestjs/nest/issues/11289

## What is the new behavior?
User can bring in custom printer. for example.
```
function setLogger() {
  const logger = new ConsoleLogger();
  logger.setCustomPrinter((level, msg) => {
    if (level === 'error') {
      console.error(msg);
    } else {
      console.log(msg);
    }
  });
  return logger;
}

const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter(), {
  logger: setLogger(),
});
```

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by micalevisk — CHANGES_REQUESTED** [review]
please undo the deletion of `./package-lock.json` file

**Comment by jmcdo29** [comment]
Why bring in more of an API and complexity to the class when this is already manageable via extending the class or with a custom logger?

**Comment by ianzone** [comment]
> Why bring in more of an API and complexity to the class when this is already manageable via extending the class or with a custom logger?

because I couldn't find a easy way of solving this issue https://github.com/nestjs/nest/issues/11289

**Comment by ianzone** [comment]
> please undo the deletion of `./package-lock.json` file

restored

**Comment by jmcdo29** [comment]
> because I couldn't find an easy way to solve this issue https://github.com/nestjs/nest/issues/11289, and I prefer not to reinvent the ConsoleLogger just for changing the printer.

You wouldn't be "reinventing" it, just changing a _part_ of the logic. The `printMessage` is `protected` meaning child classes can override the method and use their own version

```ts
export class ConsoleLogConsoleLogger extends ConsolerLogger {

  protected printMessages(
    messages: unknown[],
    context = '',
    logLevel: LogLevel = 'log',
    writeStreamType?: 'stdout' | 'stderr',
  ) {
    messages.forEach(message => {
      const pidMessage = this.formatPid(process.pid);
      const contextMessage = this.formatContext(context);
      const timestampDiff = this.updateAndGetTimestampDiff();
      const formattedLogLevel = logLevel.toUpperCase().padStart(7, ' ');
      const formattedMessage = this.formatMessage(
        logLevel,
        message,
        pidMessage,
        formattedLogLevel,
        contextMessage,
        timestampDiff,
      );

      if (logLevel === 'error') {
        console.error(formattedMessage);
      } else {
        console.log(formattedMessage);
      }
    });
  }
```

This acts exactly like you want without any modification to Nest's code

**Comment by ianzone** [comment]
> > because I couldn't find an easy way to solve this issue #11289, and I prefer not to reinvent the ConsoleLogger just for changing the printer.
> 
> You wouldn't be "reinventing" it, just changing a _part_ of the logic. The `printMessage` is `protected` meaning child classes can override the method and use their own version
> 
> ```ts
> export class ConsoleLogConsoleLogger extends ConsolerLogger {
> 
>   protected printMessages(
>     messages: unknown[],
>     context = '',
>     logLevel: LogLevel = 'log',
>     writeStreamType?: 'stdout' | 'stderr',
>   ) {
>     messages.forEach(message => {
>       const pidMessage = this.formatPid(process.pid);
>       const contextMessage = this.formatContext(context);
>       const timestampDiff = this.updateAndGetTimestampDiff();
>       const formattedLogLevel = logLevel.toUpperCase().padStart(7, ' ');
>       const formattedMessage = this.formatMessage(
>         logLevel,
>         message,
>         pidMessage,
>         formattedLogLevel,
>         contextMessage,
>         timestampDiff,
>       );
> 
>       if (logLevel === 'error') {
>         console.error(formattedMessage);
>       } else {
>         console.log(formattedMessage);
>       }
>     });
>   }
> ```
> 
> This acts exactly like you want without any modification to Nest's code

thanks for your suggestion, but updateAndGetTimestampDiff is private, do you suggest I change it to protected and do another PR?

**Comment by jmcdo29** [comment]
I'd prefer the change to protected

**Pull request closed without merging**
