### PR TITLE
docs: add portuguese document

### PR DESCRIPTION
**Pull request by gustavonobreza**
## PR Checklist
Please check if your PR fulfills the following requirements:
- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: add portuguese document

## What is the current behavior?
This project don't has a Portuguese translation.

## What is the new behavior?
I introduce the Portuguese translation. So people from countries like: Brazil, Portugal, Angola, Mozambique and others can read the guide in their maternal language.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
Nothing 😁

### CODE REVIEW

**Comment by yepes** [comment]
@kamilmysliwiec i really think you should be accepting translations from the community. I guess it would be difficult to maintain and to have them reach a minimum quality level, but a lot of people would benefit from that. 

You said in the other comment that for European countries that are close to English language won’t be any translation. Spanish is totally different from English, and while most of the Spaniards (as I) can understand technical docs, language barrier is still a thing.

**Comment by gustavonobreza** [comment]
I agree with @yepes ' idea. I think an important barrier to getting to know the framework would be broken. Among the Latin languages, the differences are already considerable, when it comes to English, the languages ​​are even more distant. 
I'm new to the tech world and my English is not that good but with the help of Google Translate I can understand the NestJS documentation, what I'm trying to say is that I wouldn't have to need an external tool to teach someone else how to use it.

**Comment by jmcdo29** [comment]
@yepes @gustavonobreza **If** the Nest team were to take on managing a translation of the docs, what languages would be and wouldn't be included? How would we generate these translations? I personally only have a loose grasp on German, and absolutely no knowledge of Latin based languages. 

As our docs are open source, it would be completely fine for a community member to take the existing docs and host them elsewhere as a translated docs site. 

It's understandable that docs in your native language would make it easier to pick up the framework, we just don't have the manpower to be able to create these translations, or determine a hosting solution for how we could serve the translations as well (at least at the moment).

**Comment by yepes** [comment]
I guess that’s where the community comes in.

**Comment by kamilmysliwiec** [comment]
And how would we make sure that things are explained in a proper way if we don't understand the language ourselves? Since everyone on the team has at least a basic understanding of English, we can support each other while reviewing contributions and that would be impossible if we started accepting different versions.

**Pull request closed without merging**
