### PR TITLE
chore(testing, websockets): mark facing apis public

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
In continuation of PR https://github.com/nestjs/nest/pull/10975, https://github.com/nestjs/nest/pull/11032, https://github.com/nestjs/nest/pull/11033

Not all user-facing APIs are annotated with `@publicApi`, which, from contributors like myself who help in NestJS, could lead to some confusion as to which APIs can be changed without breaking any changes.

Add `@publicApi` in:
 - testing
 
## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.

### CODE REVIEW

**Review by micalevisk — APPROVED** [review]

**Comment by Tony133** [comment]
just a doubt these classes here are not public right:

- `TestingInstanceLoader`(https://github.com/nestjs/nest/pull/11034/files#diff-98cced122099fecfe43051f701076e3f1c04c0672c539273da4f788425b5ea60)
- `TestingModuleBuilder` (https://github.com/nestjs/nest/pull/11034/files#diff-c6f212447d6f0317f161a6c240c63cd76facb852df3db139d9719bc361b65b04) 

?

**Comment by micalevisk** [comment]
we can join this with #11033 or vice-versa to avoid multiple PRs

**Comment by Tony133** [comment]
I preferred to have them separated to do the reviews first.
But I can join them together, no problem

do you know if these are public
- TestingInstanceLoader(https://github.com/nestjs/nest/pull/11034/files#diff-98cced122099fecfe43051f701076e3f1c04c0672c539273da4f788425b5ea60)
- TestingModuleBuilder (https://github.com/nestjs/nest/pull/11034/files#diff-c6f212447d6f0317f161a6c240c63cd76facb852df3db139d9719bc361b65b04)

?

Anyway, should still be missing there to check if @ApiPublic is there:

- `@nestjs/core`
- `@nestjs/microservices`
- `@nestjs/websocket`

**Comment by Tony133** [comment]
I have update this PR I added `@publicApi in websockets, do check if there is anything I missed

at the moment i removed the `@publicApi` in 
- `TestingInstanceLoader`

If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.

**Comment by micalevisk** [comment]
I guess you missed these:

- `connected-socket.decorator.ts`
- `socket-gateway.decorator.ts`
- `subscribe-message.decorator.ts`
- `ws-response.interface.ts`

**Pull request merged**
