### PR TITLE
Add Lerna functionality

### PR DESCRIPTION
**Pull request by wbhob**
This PR will use lerna for managing the monorepo. This addresses #68. I have mapped the `npm publish` command to `lerna publish`, so there should not be much difference.

*Important note*: I have mapped lerna to `src`. I don't have a valid build command on the current repo, so change the property in `lerna.json` to whatever the build directory is.

### CODE REVIEW

**Comment by wbhob** [comment]
Fixed merge conflicts

**Comment by kamilmysliwiec** [comment]
Hi @wbhob,
I appreciate your work but honestly, I don't see the reason why we need an additional tool to manage only 5 repos 🙁 Lerna is great, but we don't need it since all of the repositories may have a different release number.

**Comment by wbhob** [comment]
So that’s the thing: they should all have the same release number, because they are codependent. It will get very confusing VERY fast if there are more packages or some packages have minor versions. Like angular, it’s kmportant to have every package on the same version for developer experience.

**Comment by wbhob** [comment]
@kamilmysliwiec can you see my previous comment and tell me your thoughts?

**Comment by MonsieurMan** [comment]
I'm on par with wbhob, if packages comes as a bundle they should definitely have the same version number even if no changes were introduced, it's going to be a hell if we have to keep track of which version works with which other.

**Comment by kamilmysliwiec** [comment]
Thanks @wbhob @MonsieurMan - you convinced me 🙂 Lerna is here now

**Pull request closed without merging**
