### PR TITLE
feat(@nestjs/core) Nest Router, a Utility Package

### LINKED ISSUE #255: Global prefix for a module / route tree
Hi,

there is an older issue, which got implemented: https://github.com/nestjs/nest/issues/40 - allowing to 
`setGlobalPrefix('api')`
on the app instance.

This is a very neat feature and since I'm looking to create some sort of a "route tree", it would be great to set some "route extending strategy".

Say I want to create a route tree like this:
-> api (from app.setGlobalPrefix)
--> /users (UsersModule with prefix 'users' for all of it's 'children' modules and controllers)
---> /posts (PostsModule with prefix 'posts' for all of it's 'children' modules and controllers)
----> /comments (Now I could declare a CommentsController with route 'comments' and this controller's route would be composed from all of the ancestors above, in this case: 'api/users/posts/comments'
----> /upvotes (this one would then be 'api/users/posts/upvotes')

that means I'd like to somehow set the 'module route prefix' for all of it's children's modules & controllers.

If there's already a way to achieve this, please point me in the right direction, otherwise it would be pretty nice to have this.

Thanks

### PR DESCRIPTION
**Pull request by shekohex**
This PR will make it easy to add a `Path` Property to a Module without even editing the Public API of Nest.
the Idea, anyone needs to make a  `Routes Tree` will use an external package [nest-router](https://github.com/shekohex/nest-router).
this package is well tested and Documented.
this PR will close #255 .

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
hi @shekohex,
I really enjoy the idea behind `nest-router`, it's really cool stuff, but as I said a few times already, there's no place for `path` in `@Module()` decorator.

**Comment by shekohex** [comment]
Hi @kamilmysliwiec , Who said that we will have the `path` property in `@Module()` decorator, 
there is no need to do this, and also there is no Public API will provide this.
all we need the ability to read only the `path` metadata from the module `metatype` which the `nest-router` will provide.
any one needs to make the routes tree , will only needs the `nest-router` package, that's it, 
the `RouterModule` will provide the `path` property and write it to Module metatype.
at the end, this PR changes will be only used if the `RouterModule` used.

**Comment by kamilmysliwiec** [comment]
Alright, I'm sorry @shekohex, 40 hours without sleep is definitely too much

**Comment by kamilmysliwiec** [comment]
I'll review as soon as possible :)

**Comment by kamilmysliwiec** [comment]
Cool stuff @shekohex, merged. Looking forward to `nest-router`. Btw, I think that importing `RouterModule.forRoutes()` instead of calling it in the constructor will be better 🙂

**Comment by shekohex** [comment]
I will :+1: , Thanks.

**Comment by shekohex** [comment]
this package is now ready to be used [nest-router](https://github.com/shekohex/nest-router), I'd love to add it in docs in `RECIPES` section

**Comment by kamilmysliwiec** [comment]
@shekohex looking forward to it!! feel free to create PR, will merge as quickly as possible 🎉

**Comment by shekohex** [comment]
Hi @kamilmysliwiec , I Just Finished the docs about This Module , and created the PR https://github.com/nestjs/docs.nestjs.com/pull/45

**Comment by thaoula** [comment]
Hey guys,

Is this working in V5? 
https://github.com/shekohex/nest-router/issues/8

Regards,
Tarek

**Pull request merged**
