### PR TITLE
docs(samples): add GraphQL Federation samples

### PR DESCRIPTION
**Pull request by Flusinerd**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X ] Other... Please describe: Sample apps for GraphQL Federation (#4686)
```

## What is the current behavior?
No samples available for graphql-federation

Issue Number: #4686 

## What is the new behavior?

Added three sample apps for code-first and schema-first approach each according to the [federation docs](https://docs.nestjs.com/graphql/federation)

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X ] No
```

## Other information
N/A

### CODE REVIEW

**Comment by Flusinerd** [comment]
Looks like the samples CI pipeline fails, because the samples I added are three sub folders inside the sample/*/ directory. 

Any idea on how to restructure the samples?

**Comment by kamilmysliwiec** [comment]
Thanks for your contribution! Maybe we can just update the `samples` script instead of restructuring the example?

**Comment by Flusinerd** [comment]
That could be a option as well 👍🏻

**Comment by Flusinerd** [comment]
Okay I modified the gulp file for the samples: a39b2c2
It checks now if the directory contains a ``package.json`` otherwise goes down one directory

**Comment by Flusinerd** [comment]
Finally got it working, sorry about the mess in the commit headers :)

**Comment by kamilmysliwiec** [comment]
Thanks @Flusinerd! I'll review this PR as soon as I can

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
