### PR TITLE
chore(): update deps platform fastify

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: 
https://github.com/nestjs/nest/issues/9899

## What is the new behavior?
The dependencie `point-of-view@6.3.0` has been deprecated  see [here](https://www.npmjs.com/package/point-of-view)
replaced with `@fastify/view@7.0.0` link repo: https://github.com/fastify/point-of-view

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

screenshot1

screenshot

### CODE REVIEW

**Comment by liaoliaots** [comment]
changes may be needed:

https://github.com/nestjs/nest/blob/master/packages/platform-fastify/adapters/fastify-adapter.ts#L417
https://github.com/nestjs/nest/blob/master/packages/platform-fastify/interfaces/external/point-of-view-options.interface.ts#L5

**Comment by liaoliaots** [comment]
changes may be needed:

https://github.com/nestjs/nest/blob/master/packages/platform-fastify/adapters/fastify-adapter.ts#L417
https://github.com/nestjs/nest/blob/master/packages/platform-fastify/interfaces/external/point-of-view-options.interface.ts#L5

**Comment by Tony133** [comment]
hi @liaoliaots, I check if any other changes are needed. Thanks for reporting 👍

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
