### PR TITLE
feat(microservices): Add BrokersFunction to KafkaConfig brokers property

### PR DESCRIPTION
**Pull request by smhmayboudi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #5633

## What is the new behavior?
You can add a function to set brokers.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by galesky** [comment]
Hello @smhmayboudi,

I think you referenced the wrong issue, isn't https://github.com/nestjs/nest/issues/5633 ?

**Comment by smhmayboudi** [comment]
Yes, you are right.

**Comment by smhmayboudi** [comment]
Hello @galesky, Yes you are right. I fixed the PR.

**Comment by kamilmysliwiec** [comment]
Can you resolve merge conflicts? @smhmayboudi

**Comment by kamilmysliwiec** [comment]
Can you resolve merge conflicts? @smhmayboudi

**Pull request merged**
