### PR TITLE
build(): Refactor Gulpfile to TS

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The Gulpfile is quite messy. This is because all the tasks are defined in one file, and it is not written in TypeScript.

## What is the new behavior?
Rewrites the Gulp tasks to TypeScript and refactor them into dedicated files `tools/gulp/tasks`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other
This PR is inspired by [angular/components](https://github.com/angular/components)s build tasks

### CODE REVIEW

**Comment by marcus-sa** [comment]
Why not get rid of Gulp completely? It's unnecessary and obsolete.

**Comment by BrunnerLivio** [comment]
@marcus-sa 
> Why not get rid of Gulp completely? It's unnecessary and obsolete.
Would not say its obsolete. Many projects, including angular/components still use it (they use it in combination with Bazel).
It suits our task for the time being. Though Bazel is definitely worth an investigation. Haven't used it yet - therefore I can not give feedback whether it is suited for Nest - but I think we can start a conversation about that.

For the time being, lets stick with Gulp.

**Comment by marcus-sa** [comment]
Using https://garden.io or similar would also ease the integration of sample projects and e2e testing and help getting rid of gulp completely.
(We use it for our entire dashboard app at work)

**Comment by kamilmysliwiec** [comment]
Great job ❤️

**Pull request merged**
