### PR TITLE
feat(common): api decorator

### PR DESCRIPTION
**Pull request by mohamadrezamomeni**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by mohamadrezamomeni** [comment]
Hello
I want to merge several decorators because I think it is easier to use one decorator than to use many decorators and also I want to merge swagger decorator with this decorator.

I am glad to know your opinion @kamilmysliwiec

**Comment by micalevisk** [comment]
I believe this was discussed in the past

Also, this could live as a 3rd-party lib, right?

**Comment by mohamadrezamomeni** [comment]
> I believe this was discussed in the past
> 
> Also, this could live as a 3rd-party lib, right?


I made this decorator in my own library which is used in my company

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.

**Pull request closed without merging**
