### PR TITLE
feat(microservices): add tcp raw data processing capabilities

### PR DESCRIPTION
**Pull request by jeanbmar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/7288

Current Microservices implementation of TCP server and client does not allow to process raw TCP packets.
Incoming data are processed by the `JsonSocket` helper which requires a specific format for incoming data in order to emit messages.

## What is the new behavior?

The new behavior moves the core TCP logic from `JsonSocket` into the abstract `TcpSocket`.
`TcpSocket` is extensible and allows NestJS users to define their own socket class in order to parse and send data using a custom format.

In order to implement their custom socket class, NestJS users have to:
 - implement the abstract `TcpSocket.prototype.handleSend` method to write data to the underlying net.Socket 
 - implement the abstract `TcpSocket.prototype.handleData` method to process raw data and emit messages
 - call `TcpSocket.prototype.emitMessage` from inside `TcpSocket.prototype.handleData` to emit NestJS string messages

The new `JsonSocket` is a direct example of `TcpSocket` implementation.

In addition, a new `socketClass` option is added to the `Transport.TCP` transport options (default to `JsonSocket`) to pass the custom socket implementation to `ClientTCP` and `ServerTCP` instances.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

### CODE REVIEW

**Comment by jeanbmar** [comment]
The PR is not complete yet but it created for tracking and discussion. I will update on completion.

**Comment by jeanbmar** [comment]
I've edited the solution with additional details. PR is ready for technical review.

**Comment by jeanbmar** [comment]
There's an additional point I would like to discuss which could be integrated to this PR.

The way errors are handled in the current JsonSocket implementation seems wrong to me.
https://github.com/nestjs/nest/blob/2df2cff34f423e44e655efd1c75b0571afef9db0/packages/microservices/helpers/json-socket.ts#L66-L72

This implementation won't close the underlying socket if the client doesn't answer with an end of transmission packet. Which is totally possible when we got an error in the first place.

I suggest the following change:

```js
try {
      this.handleData(data);
    } catch (e) {
      this.socket.destroy(e);
    }
```

Calling destroy this way will trigger the socket error and close events automatically.

**Comment by kamilmysliwiec** [comment]
> I suggest the following change:

@jeanbmar would you like to create a follow-up PR?

LGTM

**Pull request merged**
