### PR TITLE
chore(microservice): updated nats options

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number:  #6054

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, updated nats options

### CODE REVIEW

**Review by jmcdo29 — APPROVED** [review]

**Comment by MickL** [comment]
Can this be merged as it only adds properties to the interface?

**Comment by jmcdo29** [comment]
It looks good to me. We have to wait for Kamil to merge it though.

**Comment by MickL** [comment]
Can one confirm that the options do not take effect? I tried timeout but no error is thrown:

```ts
const a = await this.natsClient.send('myEvent', { hello: 'world' }).toPromise();
```

Also I tried token but it does not connect:

```ts
providers:   [
    // ...
    {
      provide:    NATS_SERVICE,
      useFactory: (configService: ConfigService) => ClientProxyFactory.create({
        transport: Transport.NATS,
        options:   {
          url:     configService.get<string>('NATS_URL'),
          timeout: 2000,
          token: 'abc123',
        },
      }),
      inject:     [ConfigService],
    },
```

**Comment by jmcdo29** [comment]
[Here is the code for the client proxy factory](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-proxy-factory.ts) and [this is the code that creates the NATS client](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts#L46). If options are passed, they should be passed on to the `nats.connect()` method. [This is the underlying `connect$` method that all the microservice packages make use of to allow for the use of RxJS](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-proxy.ts#L103)

**Comment by MickL** [comment]
@jmcdo29 I just updated my comment it is just the timeout

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
