### PR TITLE
feat(common): add the ability to set some extra metadata about returned files

### PR DESCRIPTION
**Pull request by jmcdo29**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Right now, we can just return a file and have to inject `@Res({ passthrough: true })` to update the content-type and disposition

## What is the new behavior?

We can pass these options to the `StreamableFile` constructor and let Nest take care of the work for devs

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
image

@jmcdo29 integration tests are failing atm

**Comment by jmcdo29** [comment]
> image
> 
> @jmcdo29 integration tests are failing atm

That's super weird. Won't fail for me locally. I'll try to dig in a bit and see what's going on.

**Comment by jmcdo29** [comment]
Interesting. It looks like the new `getHeaders` method I added to the `StreamableFile` isn't being found during the e2e test. I've noticed locally I need to run `npm run build` to make sure the integration tests use the latest code. Is that how it should be, or are we pointing at something wrong?

**Comment by kamilmysliwiec** [comment]
Check out this commit @jmcdo29  https://github.com/nestjs/nest/commit/f69d157013d48e2ed4e74fbea51f5a749e300ea1#diff-7601c6884e46e07a23aae0fea72039261b51395017f5ef74f58bb7a2519e5cb1R283-R290

To fix e2e tests, I had to move `body = body.getStream();` below ifs (`body` wasn't an instance of the `StreamableFile` anymore)

**Comment by jmcdo29** [comment]
Oh shoot! I see what happened now. Good catch.

**Pull request merged**
