### PR TITLE
sample(14-mongoose): update name database mongodb

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
update database providers for mongodb

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
This PR, update database providers for mongodb(see screenshot)
screenshot

### CODE REVIEW

**Comment by Tony133** [comment]
I changed the version of mongoose due to this problem (see screenshot), at the moment I only found this solution, with version `5.13.8` of `mongoose` this problem is not given.

screenshot

if you find other solutions let me know. 👍

**Comment by kamilmysliwiec** [comment]
We shouldn't downgrade the mongoose version. Can you revisit this PR & see if there are other options we can pass to avoid warnings?

**Comment by Tony133** [comment]
Ok, I updated the mongoose version to `6.0.8` and the warnings are gone, they will have been removed or eliminated with the latest versions.
 I just changed the name of the mongodb database, to match that of docker-compose, as it was different.

**Comment by kamilmysliwiec** [comment]
LGTM thanks!

**Pull request merged**
