### PR TITLE
refactor(): refactored  isObject function

### PR DESCRIPTION
**Pull request by rubiin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by rubiin** [comment]
Simple , readable and shorter with same results

**Comment by micalevisk** [comment]
but doesn't behave the same (strictly speaking):

```js
class Foo {
  get [Symbol.toStringTag]() { return 'bar' }
}

const isUndefined = obj=> typeof obj === 'undefined';
const isNil = val => isUndefined(val) || val === null;


const fn = new Foo()
console.table({
  current: !isNil(fn) && typeof fn === 'object',
  new: Object.prototype.toString.call(fn) === '[object Object]',
})
/*
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│ current │  true  │
│   new   │ false  │
└─────────┴────────┘
*/
```

**Comment by micalevisk** [comment]
a valid refactoring would be renaming those `fn` parameters to something more generic like `val`

**Comment by ZanMinKian** [comment]
```js
const d = new Date();
console.log(Object.prototype.toString.call(d)); // '[object Date]'
```
Not behave the same.

Here is the implementation of `class-validator`: https://github.com/typestack/class-validator/blob/develop/src/decorator/typechecker/IsObject.ts.

**Pull request closed without merging**
