### PR TITLE
sample(12-graphql): add logger

### PR DESCRIPTION
**Pull request by rubiin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Can we stick to the convention from other samples? Check for example 01-cats-app sample

**Comment by kamilmysliwiec** [comment]
Also, please rebase to get the latest changes from master. The `12-graphql-apollo` no longer exists

**Comment by rubiin** [comment]
sure

**Comment by rubiin** [comment]
@kamilmysliwiec why are we using console.log instead of the default logger from nestjs package?

**Pull request closed without merging**
