### PR TITLE
bugfix(microservices): let use unicode characters in TCP Microservice…

### PR DESCRIPTION
**Pull request by ivibe**
… messages

add own json-socket implementation

https://github.com/nestjs/nest/issues/1734

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/1734

## What is the new behavior?
Unicode characters in TCP Microservice messages don't cause errors

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

The core algorithm was borrowed from original json-socket package (https://github.com/sebastianseilund/node-json-socket). Basically all unnecessary code was removed, only the core functionality was kept.

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Looking good. I dug a bit into the `json-socket`: Creating a PR on the repo seems to be not worthy, since it looks to be unmaintained. There is a even a [pending PR for such a fix](https://github.com/sebastianseilund/node-json-socket/pull/46) and a [fork on npmjs of the bugfix](https://www.npmjs.com/package/json-socket-international). So either we depend on a package which is badly adopted (according to the npm downloads), maintain it directly in `@nestjs/microservices` or in a seperate repository.

**Comment by kamilmysliwiec** [comment]
@BrunnerLivio see my response here https://github.com/nestjs/nest/issues/1734

**Comment by kamilmysliwiec** [comment]
Thank you :) LGTM

**Comment by ivibe** [comment]
Glad to help!

**Pull request merged**
