### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by MaxWithU**
latest mysql image can't access login

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kibertoad** [comment]
@MaxWithU Could you please clarify what do you mean by "can't access login"?
I would recommend using at least 5.7 - it is what cloud offerings host for you by default, hence it is likely to be a more popular option in non-legacy systems.

**Comment by MaxWithU** [comment]
image

press `docker-compose up -d` and `npm start` ,   will throw an exception
so I set a old version

**Comment by kibertoad** [comment]
@MaxWithU Yeah, I think it's a known incompatibility with Node MySQL driver: https://github.com/mysqljs/mysql/issues/2002
5.7 or just 5 (to use latest) should be fine.

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
