### PR TITLE
test(core): :white_check_mark: added tests for checking durability and staticity calculation when circular dependency

### PR DESCRIPTION
**Pull request by vizio360**
Added test for staticity calcuation when circular dependency present

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: Added unit tests

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Added a few new unit tests to verify that the calculation of isTreeStatic and isTreeDurable is correct even for circular dependencies.

### CODE REVIEW

**Comment by vizio360** [comment]
@kamilmysliwiec not sure if you want to add this unit test, I think it would be helpful, also wondering if another test should be added to makes sure durability works as well for circular dependencies.

**Comment by kamilmysliwiec** [comment]
This issue would have been caught with the integration test we already have in place (that's why I didn't add a dedicated unit test). I must have missed it at first, as I was merging a few PRs at once 🥲

**Comment by vizio360** [comment]
ok, sure the integration tests cover it, but if there was a unit test, making changes to the instance_wrapper class would be easier as most scenarios will be covered without having to run integration tests and you will have a shorter feedback loop.
Plus I find the unit test to be more succinct.

**Comment by kamilmysliwiec** [comment]
If you want to finish this PR I'd be more than happy to merge it in

**Comment by kamilmysliwiec** [comment]
Great work! 💪

**Comment by vizio360** [comment]
> Great work! 💪

hopefully this one has not broken anything :grin:

**Pull request merged**
