### PR TITLE
utils: simplify map + flat in injections providers

### PR DESCRIPTION
**Pull request by Connormiha**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
I did a little optimization. `map`+`flat` can be replaced by single `flatMap`.

### CODE REVIEW

**Review by micalevisk — APPROVED** [review]

**Comment by micalevisk** [comment]
there's another one: https://github.com/nestjs/nest/blob/518e644f8688334f496d793cfb44e2ea7ad738e5/packages/core/middleware/routes-mapper.ts#L89-L112

not sure if it will look better

**Comment by Connormiha** [comment]
> there's another one:
> 
> https://github.com/nestjs/nest/blob/518e644f8688334f496d793cfb44e2ea7ad738e5/packages/core/middleware/routes-mapper.ts#L89-L112
> 
> not sure if it will look better

I can make changes in this PR if necessary, or create a new one.

**Comment by micalevisk** [comment]
@Connormiha please change in this PR

**Review by micalevisk — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
lgtm

**Pull request merged**
