### PR TITLE
feat(microservices): Allow RegExps in Patterns for Kafka

### LINKED ISSUE #3083: It is not possible to use RegEx for event matching on the @EventPattern() adn @MessagePattern()
## Bug Report
.

## Current behavior
It is not possible to use a RegEx for event and message patterns.  This is possible when using KafkaJS library but is not possible in NestJS

## Input Code

Having a controller emitting a message `'pre-notify-post'` 

```ts
@Post('notify-with-regex')
  async sendNotificationForRegExMatching(): Promise<any> {
    return this.client.emit('pre-notify-post', { notify: true });
  }
```
Also having a controller with the event handler and expecting messages that match the regular expression of `/.*notify.*/` :

```ts
 @EventPattern(/.*notify.*/)
  secondEventHandler(data: any) {
    KafkaController.IS_NOTIFIED_WITH_REGEX = data.value.notify;
  }
```
Currently, the event handler never gets called, because the handler is not matched using regular expressions.

## Expected behavior
It is expected to listen to events and messages by using RegEx patterns. This is possible in KafkaJS  library and it is useful when having a set of a topic that the consumer wants to listen to.

> Alternatively, you can subscribe to multiple topics at once using a RegExp:
> 
> await consumer.connect()
> await consumer.subscribe({ topic: /topic-(eu|us)-.*/i })

https://kafka.js.org/docs/consuming

## Possible Solution
This could be fixed by getting the matching routes.

## Environment
Nest version: 6.7

### PR DESCRIPTION
**Pull request by edeesis**
closes #3083

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
RegExps could be added and the Typescript would compile, but at runtime, you'd get an error: 

```
The request attempted to perform an operation on an invalid topic
KafkaJSProtocolError: The request attempted to perform an operation on an invalid topic
```

because normalizePattern in Server.ts would map a RegExp to the string "{}"

Issue Number: #3083 

## What is the new behavior?

Now RegExp is allowed for Kafka, and the same handler can be used for multiple topics that match the pattern.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

N/A

### CODE REVIEW

**Comment by edeesis** [comment]
Closing for rework

**Comment by nhomble** [comment]
hi @edeesis 

Did you get offline feedback on this change? Can I help out?

**Comment by edeesis** [comment]
I was unable to get this to pass all tests and such, and ended up going with another approach in my project that didn't need this feature.

**Comment by edeesis** [comment]
I remember now that the problem comes down to how the message patterns are matched to the controller methods.

It wasn't immediately apparent how you can relate it in both directions.

**Pull request closed without merging**
