### PR TITLE
sample(17-mvc-fastify): removed unused dependencies

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Removed unused dependencies ( dependencies dev `@types/ws`, `@types/socket.io`, `@types/socket.io-redis`)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
This PR, Removed `@types/ws`, `@types/socket.io`, `@types/socket.io-redis` dependencies  dev as the use of websockets is not used.

### CODE REVIEW

**Comment by jmcdo29** [comment]
In the future, could you lump these together? Just to make the review quicker? Love seeing the cleanup, but as these are pretty quick changes it should be easy enough to have them all in a single PR

**Comment by Tony133** [comment]
Yeah sure, no problem 👍,I already wanted to do this but thought it was a little confusing to mix the samples all together, however I will do this from the next PR as I noticed there are more samples to clean with some unnecessary dependencies.

**Comment by Tony133** [comment]
I did a new PR [here](https://github.com/nestjs/nest/pull/8888) with two other examples, where I noticed some unused dependencies, I grouped them together, like you told me 👍

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
