### PR TITLE
feat(common): json logger and a few other improvements

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/11189 https://github.com/nestjs/nest/issues/10342 https://github.com/nestjs/nest/issues/13841

## What is the new behavior?

Default settings:

image

JSON:

```ts
const app = await NestFactory.create(AppModule, {
  logger: new ConsoleLogger({
    json: true
  }),
});
```

image

JSON + colors:

image

JSON + colors + compact mode disabled:

image

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by mickaeltr** [comment]
Hello @kamilmysliwiec, thanks for this nice feature!

It seems that JSON logs containing a stacktrace are split into multiple lines. Here is an example that I saw in my server logs, that was not properly processed by Datadog, because of the multiple lines:

```
2025-02-19 18:59:28.481618045 +0100 CET [web-1] { level: 'error', pid: 27, timestamp: 1739987968398, message: ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
2025-02-19 18:59:28.481630766 +0100 CET [web-1] at Callback.<instance_members_initializer> (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:125:12)
2025-02-19 18:59:28.481631916 +0100 CET [web-1] at new Callback (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:130:3)
2025-02-19 18:59:28.481632546 +0100 CET [web-1] at CallbackRegistry.create (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:28:22)
2025-02-19 18:59:28.481633225 +0100 CET [web-1] at Connection._rawSend (/app/node_modules/puppeteer-core/src/cdp/Connection.ts:129:22)
2025-02-19 18:59:28.481633774 +0100 CET [web-1] at CdpCDPSession.send (/app/node_modules/puppeteer-core/src/cdp/CdpSession.ts:103:29)
2025-02-19 18:59:28.481634286 +0100 CET [web-1] at NetworkManager.addClient (/app/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:110:14)
2025-02-19 18:59:28.481634880 +0100 CET [web-1] at FrameManager.initialize (/app/node_modules/puppeteer-core/src/cdp/FrameManager.ts:215:30)
2025-02-19 18:59:28.481653995 +0100 CET [web-1] at CdpPage.#initialize (/app/node_modules/puppeteer-core/src/cdp/Page.ts:349:28)
2025-02-19 18:59:28.481663454 +0100 CET [web-1] at Function._create (/app/node_modules/puppeteer-core/src/cdp/Page.ts:105:27)
2025-02-19 18:59:28.481664439 +0100 CET [web-1] at /app/node_modules/puppeteer-core/src/cdp/Target.ts:258:24, context: 'ExceptionsHandler' }
2025-02-19 18:59:30.282824354 +0100 CET [web-1] { level: 'error', pid: 27, timestamp: 1739987970281, message: ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
2025-02-19 18:59:30.282834111 +0100 CET [web-1] at Callback.<instance_members_initializer> (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:125:12)
2025-02-19 18:59:30.282842900 +0100 CET [web-1] at new Callback (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:130:3)
2025-02-19 18:59:30.282862838 +0100 CET [web-1] at CallbackRegistry.create (/app/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:28:22)
2025-02-19 18:59:30.282878796 +0100 CET [web-1] at Connection._rawSend (/app/node_modules/puppeteer-core/src/cdp/Connection.ts:129:22)
2025-02-19 18:59:30.282885043 +0100 CET [web-1] at CdpCDPSession.send (/app/node_modules/puppeteer-core/src/cdp/CdpSession.ts:103:29)
2025-02-19 18:59:30.282886170 +0100 CET [web-1] at NetworkManager.addClient (/app/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:110:14)
2025-02-19 18:59:30.282887113 +0100 CET [web-1] at FrameManager.initialize (/app/node_modules/puppeteer-core/src/cdp/FrameManager.ts:215:30)
2025-02-19 18:59:30.282887585 +0100 CET [web-1] at CdpPage.#initialize (/app/node_modules/puppeteer-core/src/cdp/Page.ts:349:28)
2025-02-19 18:59:30.282888008 +0100 CET [web-1] at Function._create (/app/node_modules/puppeteer-core/src/cdp/Page.ts:105:27)
2025-02-19 18:59:30.282891730 +0100 CET [web-1] at /app/node_modules/puppeteer-core/src/cdp/Target.ts:258:24, context: 'ExceptionsHandler' }
```

Please let me know if you also think it's a problem and want me to create an issue about it.

**Comment by kamilmysliwiec** [comment]
@mickaeltr any chance you could provide a minimum reproduction repository?

**Comment by mickaeltr** [comment]
Thanks @kamilmysliwiec for replying! I can work on that for sure.

Disclaimer: it may be due to my misunderstanding of the logger arguments (`stack`, `optionalParams`) which are not extensively [documented](https://docs.nestjs.com/techniques/logger)…

Anyway, I made a few tests…

# When logging a Date or an Error
```ts
logger.error(new Date("2025-01-01"));
logger.error(new Error("Houston"));
```
it produces broken log, because the message is missing quotes:
```json
{ level: 'error', pid: 23693, timestamp: 1740079180519, message: 2025-01-01T00:00:00.000Z, context: 'AppService' }
{ level: 'error', pid: 23599, timestamp: 1740078731157, message: Error: Houston
       at AppService.onModuleInit (/Users/mickael/IdeaProjects/json-logs/src/app.service.ts:8:23)
       at MapIterator.iteratee (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
       at MapIterator.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/map.ts:9:39)
       at IteratorWithOperators.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:19:28)
       at Function.from (<anonymous>)
       at IteratorWithOperators.toArray (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:227:22)
       at callOperator (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
       at callModuleInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
       at NestApplication.callInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application-context.js:242:50)
       at async NestApplication.init (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application.js:100:9), context: 'AppService' }
```
# When logging a string message and an Error
```ts
logger.error("1. We have a problem", new Error("Houston"));
```
it produces broken logs, since I would expect to have a single line of log for a single logger function call
```json
{ level: 'error', pid: 23215, timestamp: 1740077384750, message: '1. We have a problem', context: 'AppService' }
{ level: 'error', pid: 23215, timestamp: 1740077384750, message: Error: Houston
       at AppService.onModuleInit (/Users/mickael/IdeaProjects/json-logs/src/app.service.ts:8:47)
       at MapIterator.iteratee (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
       at MapIterator.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/map.ts:9:39)
       at IteratorWithOperators.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:19:28)
       at Function.from (<anonymous>)
       at IteratorWithOperators.toArray (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:227:22)
       at callOperator (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
       at callModuleInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
       at NestApplication.callInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application-context.js:242:50)
       at async NestApplication.init (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application.js:100:9), context: 'AppService' }
```
# When logging a string message and an error wrapped in an object
```ts
logger.error("2. We have a problem", { error: new Error("Houston") });
```
produces the same kind of broken logs:
```json
{ level: 'error', pid: 23364, timestamp: 1740077970192, message: '2. We have a problem', context: 'AppService' }
{ level: 'error', pid: 23364, timestamp: 1740077970192, message: { error: Error: Houston
          at AppService.onModuleInit (/Users/mickael/IdeaProjects/json-logs/src/app.service.ts:9:56)
          at MapIterator.iteratee (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
          at MapIterator.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/map.ts:9:39)
          at IteratorWithOperators.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:19:28)
          at Function.from (<anonymous>)
          at IteratorWithOperators.toArray (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:227:22)
          at callOperator (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
          at callModuleInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
          at NestApplication.callInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application-context.js:242:50)
          at async NestApplication.init (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application.js:100:9) }, context: 'AppService' }
```
# When logging a string message and an Error stack
```ts
logger.error("3. We have a problem", new Error("Houston").stack)
```
That looks good ✅
```json
{ level: 'error', pid: 23364, timestamp: 1740077970194, message: '3. We have a problem', context: 'AppService', stack: 'Error: Houston\n    at AppService.onModuleInit (/Users/mickael/IdeaProjects/json-logs/src/app.service.ts:10:47)\n    at MapIterator.iteratee (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)\n    at MapIterator.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/map.ts:9:39)\n    at IteratorWithOperators.next (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:19:28)\n    at Function.from (<anonymous>)\n    at IteratorWithOperators.toArray (/Users/mickael/IdeaProjects/json-logs/node_modules/iterare/src/iterate.ts:227:22)\n    at callOperator (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)\n    at callModuleInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)\n    at NestApplication.callInitHook (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application-context.js:242:50)\n    at async NestApplication.init (/Users/mickael/IdeaProjects/json-logs/node_modules/@nestjs/core/nest-application.js:100:9)' }
```

In the end I see a few problems:
- extra arguments produce multiple JSON logs
- an Error or a Date (and maybe other types), in the arguments, produces a broken JSON
- the JSON outputs use single quotes, where I would expect to always have double quotes for [maximum compatibility](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/JSON#other_notes)

Please let me know what you think and if you still need a reproduction repository.

Thanks again!

**Comment by mickaeltr** [comment]
Oops! Sorry, I had colors enabled, that explains most of the errors. 🤦‍♂️

So without colors, the only behavior that still seems weird to me, is about having multiple logs for a single logger function (when with multiple arguments).

**Pull request merged**
