### PR TITLE
refactor(common): update logger - wip

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: #10878

## What is the new behavior?
-  Moved the `ConsoleLoggerOptions` interface to a separate file, now inside the interfaces folder.
-  Moved the `LogBufferRecord` interface to a separate file, now inside the interfaces folder.
-  Created `index.ts` file inside interfaces folder.
-  Changed LogLevel

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

**Refactoring logger for next major release of NestJS  😻**

### CODE REVIEW

**Comment by Tony133** [comment]
This PR is a refactoring of the logger for the next major release of NestJS 😻 (not to be merged at the moment)

**Comment by Tony133** [comment]
I could also move this interface to a separate file 🤔https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L6L45

**Comment by kamilmysliwiec** [comment]
Note: we gotta stop moving interfaces/types around if they're public-facing (public API). Otherwise we'll be introducing breaking changes and cause more harm than good

**Comment by Tony133** [comment]
That's right, these are: https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L6L45
they are public 👍, I did not read the comment, thanks for pointing it out to me 😅

**Comment by kamilmysliwiec** [comment]
Some interfaces like LogBufferRecord are supposed to be "private" and that's why they're not located in dedicated files 😄 
Moving forward we'll stop accepting PRs where we move interfaces around. Could you revert these changes?

**Comment by Tony133** [comment]
After lunch I will update the PR

**Comment by Tony133** [comment]
I am closing this PR because it is not aligned well with the master is there are a lot of conflicts, so as not to make mistakes I prefer to close it let's follow this in a new PR #11036

**Pull request closed without merging**
