### PR TITLE
fix: kafka subscribe bad type - v10 regression

### PR DESCRIPTION
**Pull request by regevbr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  #11819

## What is the new behavior?

Remove the correct field from the type

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by micalevisk** [comment]
so there's no `topic` field on that `ConsumerSubscribeTopics` interface, right?

**Comment by regevbr** [comment]
There is but it is deprecated. The type that is referenced currently is the new one that has `topics` field in it

https://github.com/nestjs/nest/blob/8399c68b20cd76d766cd25790f662ef211e810ff/packages/microservices/external/kafka.interface.ts#L1034-L1044

I already have a PR lined up to use the new `topics` field in the code, once we merge this one and solve #11820

**Review by micalevisk — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by regevbr** [comment]
> There is but it is deprecated. The type that is referenced currently is the new one that has `topics` field in it
> 
> https://github.com/nestjs/nest/blob/8399c68b20cd76d766cd25790f662ef211e810ff/packages/microservices/external/kafka.interface.ts#L1034-L1052
> 
> I already have a PR lined up to use the new `topics` field in the code, once we merge this one and solve #11820

#11826 is migrating the code out of the deprecated usage of `topic` field

**Pull request merged**
