### PR TITLE
Add headers in messages to NATS client

### PR DESCRIPTION
**Pull request by kvandake**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
NATS messages doesn`t have headers when publishes

Issue Number: N/A

## What is the new behavior?
NATS messages have optional headers when publishes
The logics is copied from [kafka-request.serializer.ts](https://github.com/nestjs/nest/blob/master/packages/microservices/serializers/kafka-request.serializer.ts)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kvandake** [comment]
My issue - https://github.com/nestjs/nest/issues/7863

**Comment by kamilmysliwiec** [comment]
So if I understand correctly, you can now pass an object with `data` and `headers` properties if you want to set request headers. Still, the original behavior remains the same? (no `headers` means there's no requirement to wrap data in `data` object)?

**Comment by kvandake** [comment]
> So if I understand correctly, you can now pass an object with `data` and `headers` properties if you want to set request headers. Still, the original behavior remains the same? (no `headers` means there's no requirement to wrap data in `data` object)?

we can send a message using two methods:

```ts
// original behavior - message has only data
this.client.send('pattern', 12345);

// new behavior - message has headers and data
this.client.send('pattern', {
   headers: someHeaders,
   value: 12345
});
```

P.S. I can rename **value** to **data** if this behavior would be better

**Comment by kamilmysliwiec** [comment]
@kvandake in this case, PR introduces a breaking change for anyone who's been sending messages/events as objects that contain `headers` property. To avoid introducing a breaking change, we can consider providing a dedicated class, for example, `NatsMessage` which object you can pass to `#send()` or `#emit()` methods. This class would expose an interface for setting headers, etc.

pseudo-code:

```typescript
const msg = new NatsMessage(...original data to send...).addHeader()
this.client.send(msg)
```

and at the serializer level, we could extract (unwrap) the actual message to send (alongside with headers)

**Comment by kvandake** [comment]
> @kvandake in this case, PR introduces a breaking change for anyone who's been sending messages/events as objects that contain `headers` property. To avoid introducing a breaking change, we can consider providing a dedicated class, for example, `NatsMessage` which object you can pass to `#send()` or `#emit()` methods. This class would expose an interface for setting headers, etc.
> 
> pseudo-code:
> 
> ```ts
> const msg = new NatsMessage(...original data to send...).addHeader()
> this.client.send(msg)
> ```
> 
> and at the serializer level, we could extract (unwrap) the actual message to send (alongside with headers)

I did special builder for natsMessage. For example

```ts
// set nats headers from 'nats' - import { headers } from 'nats'
const natsMessage  = new NatsMessageBuilder<string>('simple message')
   .setHeader(natsHeaders)
   .build();

// set plain headers
const natsMessage  = new NatsMessageBuilder<string>('simple message')
   .setPlainHeaders({ 'header1_key': 'header1_value' })
   .build();

// set only data
const natsMessage  = new NatsMessageBuilder<string>()
   .setData('simple message')
   .build();

// send a nats message
this.client.send(natsMessage);

// and we safe original behavior
this.client.send('simple message');

```

**Comment by kamilmysliwiec** [comment]
Let me merge this branch to the `feat/msvc-message-builder` where I'll implement similar builders for a few other transport strategies. Thank you @kvandake!

**Pull request merged**
