### PR TITLE
feat(bun-ws): websocket adapter for bun runtime

### PR DESCRIPTION
**Pull request by okxiaoliang4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
websocket adapter for `bun` runtime.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by okxiaoliang4** [comment]
I'm not sure if Nest's roadmap is going to be compatible with `bun` runtime. If it's compatible, I can also try to implement the web adapter.

**Comment by kamilmysliwiec** [comment]
Wasn't Bun supposed to be 1-1 compatible with Node.js? I thought that was the principle

**Comment by okxiaoliang4** [comment]
sure. the bun runtime also can compatible `ws`, but the native bun webSocket is more faster.

**Comment by jmcdo29** [comment]
Could this adapter be managed in a third-party library rather than part of the core repo by the Nest team?

**Comment by okxiaoliang4** [comment]
sure.

**Pull request closed without merging**
