### PR TITLE
sample(get-url): add sample for get-url

### PR DESCRIPTION
**Pull request by uc4w6c**
feat #3306 

Nice to meet you
Since the PR has not been created for a long time, we created it instead.
Sorry if you have any deficiencies due to your first PR.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: sample app for get URL
```

## What is the current behavior?

Issue Number: #3306 

## What is the new behavior?
Adding samples(get URL)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Thanks for your contribution @uc4w6c.

Actually, we didn't want to create a new example for "get-url" feature, but rather add this:

```typescript
console.log(`Application is running on: ${app.getUrl()}`);
```

to every **existing** example.

**Comment by uc4w6c** [comment]
@kamilmysliwiec I'm sorry. My understanding was wrong.

Please check it because it has been fixed.
I've added in URL output to every sample.

Is it better to add it to the cli for `nest new project-name`?

**Comment by kamilmysliwiec** [comment]
Thanks!

**Comment by emirom** [comment]
> Thanks for your contribution @uc4w6c.
> 
> Actually, we didn't want to create a new example for "get-url" feature, but rather add this:
> 
> ```ts
> console.log(`Application is running on: ${app.getUrl()}`);
> ```
> 
> to every **existing** example.

app.getUrl() returns a [object promise]
promise app.getUrl()
returns the correct url

**Pull request merged**
