### PR TITLE
feat(core, common): add webdav http methods support

### LINKED ISSUE #9459: WebDAV request method support
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No issues yet.

### Describe the solution you'd like

Add PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK request method support.

### Teachability, documentation, adoption, migration strategy

express already supports these methods.

### What is the motivation / use case for changing the behavior?

If i want to serve webdav, then we must return to the original express.
It would be great if I could use the decorator directly.

### PR DESCRIPTION
**Pull request by hungtcs**
Closes #9459

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #9459

## What is the new behavior?

Add new decorators for webdav methods, like `@PropFind`

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by Nisgrak** [comment]
The support of fastify is merged already https://github.com/fastify/fastify/pull/3836. We love to see this shipped!

**Comment by johaven** [comment]
Any news on this ? Aborted ?

**Comment by jmcdo29** [comment]
image

**Comment by johaven** [comment]
Yes I saw :p Is an implementation of these decorators planned on your side ?

**Pull request closed without merging**
