### PR TITLE
fix(microservices): export ClientRMQ and ServerRMQ with correct types

### PR DESCRIPTION
**Pull request by jiayihu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Export `ClientRMQ` in `/client/index.ts` to allow importing from `@nestjs/microservices` 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by jiayihu** [comment]
TODO: I need to export also `ServerRMQ` and I think that its [`options` type](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-rmq.ts#L29) is wrong. It should be `options: MicroserviceOptions['options']`

**Comment by kamilmysliwiec** [comment]
@jiayihu feel free to add those fixes to this PR as well :)

**Comment by kamilmysliwiec** [comment]
Ping 🏓

**Comment by jiayihu** [comment]
Pong 🏓 
In fixing the options typing I've discovered a broader type error: `this.getOptionsProp<RmqOptions>(this.options, 'urls')` is wrong because the `RmqOptions` type doesn't have `urls`. It's `RmqOptions['options']` instead.

The definition of `RmqOptions` is indeed:

```ts

export interface RmqOptions {
  transport?: Transport.RMQ;
  options?: {
    urls?: string[];
    queue?: string;
    prefetchCount?: number;
    isGlobalPrefetchCount?: boolean;
    queueOptions?: any;
  };
}
```

**Comment by jiayihu** [comment]
Travis fails but the failed tests don't seem to be related to my changes 🤔

**Comment by kamilmysliwiec** [comment]
I'll take care of it! Thank you, great changes :)

**Pull request merged**
