### PR TITLE
feat(platform) multer support for fastify platform

### PR DESCRIPTION
**Pull request by gperdomor**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

File upload using Multer is only supported for `express` adapter
Issue Number: N/A

## What is the new behavior?

Add `fastify-multer` support in `@nestjs/platform-fastify`.

## Does this PR introduce a breaking change?
```
[] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by gperdomor** [comment]
@kamilmysliwiec WDYT? 😄

**Comment by kamilmysliwiec** [comment]
Thanks for the contribution. A few things:
- the original `multer` support (for express) is located in the `@nestjs/platform-express` package. Hence, we shouldn't create another lib but rather put it inside the `@nestjs/platform-fastify`
- `fastify-multer` is a too young library for now, we cannot recommend using it yet

**Comment by gperdomor** [comment]
@kamilmysliwiec updated, Multer package was removed and the files related interceptors was copied to platform-fastify. Please consider a common `@nestjs/multer` package to avoid code duplication in Nest 7

**Comment by gperdomor** [comment]
please let me know if you are ok with the new version to proceed to update the docs

**Comment by kamilmysliwiec** [comment]
Thank you for your contribution @gperdomor. We have to postpone merging though because as I said: 
> fastify-multer is a too young library for now, we cannot recommend using it yet

Anyway, feel free to move forward with the docs. Once the library gets more mature, we'll surely make use of it.

**Comment by gperdomor** [comment]
@kamilmysliwiec docs updated :D

**Comment by Flasheur111** [comment]
@kamilmysliwiec How long do you think this will take to merge this PR to master?

I am using @nestjs/platform-fastify and FileUpload in my project. In the meantime, is there a way to integrate this PR to @nestjs/platform-fastify dependency?

**Comment by zuohuadong** [comment]
@kamilmysliwiec  @gperdomor 
Any progress?

**Comment by ap-gorkun** [comment]
@kamilmysliwiec @gperdomor
fastify-multer has aged one year. WDYT now? 😄

**Comment by mubasshir** [comment]
@kamilmysliwiec any update on it? we are missing out on performance due to this small part

**Comment by gperdomor** [comment]
Thanks to everyone for for the interest in this PR, I will close this in favor of #4921 which basically is an updated version of this one

**Pull request closed without merging**
