### PR TITLE
fix(microservices) 2984 kafka reply partitions

### PR DESCRIPTION
**Pull request by mkaufmaner**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/2984

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

There have been several discrete changes made to the kafka message pattern.

1. I updated the kafka client to have an async close method so it awaits a disconnect from the server.  Need to update documentation to reflect that clients need to `await this.client.close();` within the `onModuleDestroy();` hook along with the importance of enabling shutdown hooks.

2. Instead of relying on high resolution time to determine the assignment of consumer topics and partitions a previous assignment of consumer topics and partitions is now factored into the balancing algorithm. The previous topic and minimum partition assignment is persisted in memory, within the `ClientKafka` class.  This is set upon the consumer instrumentation event `GROUP_JOIN` (https://kafka.js.org/docs/1.11.0/instrumentation-events) that is handled within `ClientKafka` class.  The `ClientKafka` class is then bound to the instantiation of the `KafkaReplyPartitionAssisgner` which can then get the previous assignments on rebalance. This way, on rebalance, the partition of a reply topic won't become orphaned from the `ClientKafka` consumer.  Need to update the documentation explaining these changes.

### CODE REVIEW

**Comment by mkaufmaner** [comment]
@kamilmysliwiec This is ready to be reviewed.  Glad to finally have the message pattern working on rebalance.

**Comment by mkaufmaner** [comment]
@kamilmysliwiec Any idea when you’ll get the chance to review this?

**Comment by kamilmysliwiec** [comment]
Thank you for this amazing contribution! LGTM

**Comment by mkaufmaner** [comment]
> Thank you for this amazing contribution! LGTM

You’re welcome and thank you for creating an amazing framework!  I will work on updating the documentation in a new PR.  Could you open up #5701 again?  That still needs to be verified and fixed.

**Comment by kamilmysliwiec** [comment]
Perfect! Looking forward to docs updates 💪  + just opened up #5701

**Comment by kamilmysliwiec** [comment]
@mkaufmaner our tests for Kafka frequently fail in CI pipeline with the following errors:

```
  Kafka transport
[Nest] 11164   - 01/12/2021, 8:41:08 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:08.547Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":1,"size":101} +6237ms
[Nest] 11164   - 01/12/2021, 8:41:08 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:08.842Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":3,"size":165} +295ms
[Nest] 11164   - 01/12/2021, 8:41:09 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:09.203Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":5,"size":230} +361ms
[Nest] 11164   - 01/12/2021, 8:41:09 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:09.562Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":7,"size":288} +359ms
[Nest] 11164   - 01/12/2021, 8:41:09 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:09.946Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":9,"size":347} +384ms
[Nest] 11164   - 01/12/2021, 8:41:10 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:10.230Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":11,"size":406} +284ms
[Nest] 11164   - 01/12/2021, 8:41:10 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:10.509Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":13,"size":451} +279ms
[Nest] 11164   - 01/12/2021, 8:41:10 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:10.813Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":15,"size":501} +304ms
[Nest] 11164   - 01/12/2021, 8:41:11 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:11.127Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":17,"size":555} +314ms
[Nest] 11164   - 01/12/2021, 8:41:12 AM   [ExceptionHandler] ERROR [Connection] Response Heartbeat(key: 12, version: 3) {"timestamp":"2021-01-12T08:41:12.579Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-server","error":"The group is rebalancing, so a rejoin is needed","correlationId":43,"size":10} +1452ms
[Nest] 11164   - 01/12/2021, 8:41:12 AM   [ExceptionHandler] ERROR [Runner] The group is rebalancing, re-joining {"timestamp":"2021-01-12T08:41:12.580Z","logger":"kafkajs","groupId":"nestjs-group-server","memberId":"nestjs-consumer-server-2cff59cb-41d9-46df-8af3-8c1b64a6bab4","error":"The group is rebalancing, so a rejoin is needed","retryCount":0,"retryTime":293} +1ms
[Nest] 11164   - 01/12/2021, 8:41:12 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:12.630Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":1,"size":107} +51ms
[Nest] 11164   - 01/12/2021, 8:41:12 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:12.967Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":3,"size":177} +336ms
[Nest] 11164   - 01/12/2021, 8:41:13 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:13.328Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":5,"size":248} +361ms
[Nest] 11164   - 01/12/2021, 8:41:13 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:13.684Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":7,"size":312} +356ms
[Nest] 11164   - 01/12/2021, 8:41:14 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:14.029Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":9,"size":377} +345ms
[Nest] 11164   - 01/12/2021, 8:41:14 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:14.418Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":11,"size":442} +389ms
[Nest] 11164   - 01/12/2021, 8:41:14 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:14.709Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":13,"size":498} +292ms
[Nest] 11164   - 01/12/2021, 8:41:15 AM   [ExceptionHandler] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2021-01-12T08:41:15.039Z","logger":"kafkajs","broker":"localhost:9092","clientId":"nestjs-consumer-client","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":15,"size":558} +329ms
    ✓ Start Kafka app (6880ms)
    2) /POST (sync sum kafka message)
    3) /POST (sync sum kafka(ish) message without key and only the value)
    4) /POST (sync sum plain object)
    5) /POST (sync sum array)
    6) /POST (sync sum string)
    7) /POST (sync sum number)
    8) /POST (async event notification)
    9) /POST (sync command create user)
    10) /POST (sync command create business
    11) /POST (sync command create user) Concurrency Test
```

and this, in turn, leads to a timeout error for all of them:

```
2) Kafka transport
       /POST (sync sum kafka message):
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/nest/integration/microservices/e2e/sum-kafka.spec.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

any ideas?

**Pull request merged**
