### PR TITLE
add boolean on KafkaConfig interface for easily support ssl

### PR DESCRIPTION
**Pull request by asyrafduyshart**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Support ssl:true for KafkaConfig options

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by asyrafduyshart** [comment]
There is two KafkaConfig options need tobe updated

**Comment by kamilmysliwiec** [comment]
We follow types defined here https://github.com/tulios/kafkajs

**Comment by kamilmysliwiec** [comment]
> Maybe i should try to make pull request to kafkajs github instead?

That would be great. Once they merge this PR, we should go ahead and merge this one as well

**Comment by asyrafduyshart** [comment]
It's already been merged! check it out [github](https://github.com/tulios/kafkajs/blob/master/types/index.d.ts)

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
