### PR TITLE
Adds support for thrown HttpErrors in ExceptionsHandler

### PR DESCRIPTION
**Pull request by craig552uk**
I'd like to be able to use HttpErrors in Controllers, like this.

```typescript
import { Controller, All } from '@nestjs/common';
import { Forbidden } from "http-errors";

@Controller('http-error')
export class HttpErrorController {
    @All()
    throwHttpError() {
        throw new Forbidden();
    }
}
```
HttpErrors is an Express dependency, so is already present in projects. https://www.npmjs.com/package/http-errors

This PR adds support for HttpErrors to the ExceptionsHandler.

NB: I have been unable to `npm test` as the test suite kills my poor underpowered laptop. Apologies if this breaks anything.

### CODE REVIEW

**Comment by Matonen** [comment]
I don't like that we add to much stuff to core. I like that core is light and user can use default implementations if it enough for them. When you need more logic then you can implement Exception handlers where you can have this PR logic. Also now we have extra third party dependency (http-errors). Other concern is that is  ExceptionsHandler used for microservices etc?

**Comment by craig552uk** [comment]
I appreciate your feedback.

I understand that I can achieve this functionality with a new Exception handler. What I'm suggesting in this PR is to offer out-of-the box support for the Exceptions used in Express and commonly used in 3rd-party Express extensions. 

There's a lot to like about this project, but I did wonder why it was decided to introduce `HttpException` when `HttpError` is already present and provides much more comprehensive tooling.

**Comment by kamilmysliwiec** [comment]
Hi @craig552uk,
Thanks for your effort. Honestly, I don't think that it's a good idea to add another stuff to the core. However, I'm gonna create some basic http errors (classes which extend `HttpException`) and provide them out of the box in the nearest future 🙂

**Comment by craig552uk** [comment]
@kamilmysliwiec 
Thanks for the reply. This sounds fair.
You have a great project guys.
-C

**Comment by kamilmysliwiec** [comment]
@craig552uk thanks Craig :)

**Pull request closed without merging**
