### PR TITLE
fix(gateways): add the socket.io types dependency

### PR DESCRIPTION
**Pull request by capitantrueno**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by Tony133 — COMMENTED** [review]
This package has been removed because it is deprecated (see [here](https://www.npmjs.com/package/@types/socket.io))

**Comment by capitantrueno** [comment]
Hi, @Tony133:

This package may be obsolete, but without it, the gateway example cannot be started. Therefore, the example needs some changes in order to run. Below is the error that appears when running `npm run start:debug`.

```bash
src/events/events.gateway.ts:10:24 - error TS2307: Cannot find module 'socket.io' or its corresponding type declarations.

10 import { Server } from 'socket.io';
                          ~~~~~~~~~~~
```
Best regads!

**Comment by Tony133** [comment]
Hi @capitantrueno, just install this [package](https://www.npmjs.com/package/socket.io),  it is not the type package as it is deprecated.

[Here](https://docs.nestjs.com/websockets/adapter) you will find the documentation that refers to the example.

Anyway, would you like to add this [package](https://www.npmjs.com/package/socket.io) instead of what you added? 
I dont know why but it was not added to package.json during last edit.

**Comment by capitantrueno** [comment]
> Hi @capitantrueno, just install this [package](https://www.npmjs.com/package/socket.io), it is not the type package as it is deprecated.
> 
> [Here](https://docs.nestjs.com/websockets/adapter) you will find the documentation that refers to the example.
> 
> Anyway, would you like to add this [package](https://www.npmjs.com/package/socket.io) instead of what you added? I dont know why but it was not added to package.json during last edit.

Yes, of course. Any solution to improve the documentation is welcome.
Best regars

**Review by Tony133 — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
