### PR TITLE
chore(serializer): changed visibility indicator

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, visibility indicator changed to protected in getContextOptions method

### CODE REVIEW

**Comment by Tony133** [comment]
reference issues: https://github.com/nestjs/nest/issues/5957

**Comment by jmcdo29** [comment]
> reference issues: #5957

@Tony133 for future reference, you can add these references in the commit message itself. Something like the following:

```sh
git commit -m "<subject>

<body> (optional)

ref: <issue_number>
"
```

Just one less notification that comes in, less manual work on the UI side, and GitHub can automatically link the issue to the PR

**Comment by Tony133** [comment]
Thanks for the advice, I have never done as many pulls as I am doing now you see NestJS to something special.

I wanted to ask you after how many pulls or contributions do you become an "official" member or contributor? always if you become? :-)

An interesting thing would also be to add it in the template when doing the pull -> https://github.com/nestjs/nest/blob/master/.github/PULL_REQUEST_TEMPLATE.md

I have maybe there already?

maybe add a question like:

```Are you referring to an issues?```

maybe it can be great help for you too

**Comment by jmcdo29** [comment]
There already is.

```md
# What is the current behavior?

Issue Number:
```

I just usually update both. As for your other questions, that's usually something that's decided on by the team. For more info [reach out to us on Discord](https://discord.gg/nestjs) so that we aren't creating more notifications here.

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
