### PR TITLE
fix(microservices): update server kafka to use producer only mode flag

### LINKED ISSUE #12206: Kafka hybrid application incorrectly initializes consumers when producerOnlyMode set to true
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When starting the hybrid application, the startup logs show that a consumer has been started and that it has joined the consumer group with id `nestjs-group-server`.

### Minimum reproduction code

https://github.com/bylethviva/nestjs-hybrid-kafka-issues

### Steps to reproduce

I used the cp-all-in-one project to run Kafka for me.

1. Download & start confluent all-in-one.
 ```
git clone https://github.com/confluentinc/cp-all-in-one.git
cd cp-all-in-one/cp-all-in-one
docker compose up --build -d
```
1. Dowload the repo I provided
1. Run npm run start:dev

At this point you'll be able to see the messages about the consumer group being joined.

Screen Shot 2023-08-08 at 3 38 45 PM

### Expected behavior

In a hybrid application, when using `app.connectMicroservice` with Kafka and I pass `producerOnlyMode: true`, I expect that option to be respected. If I change my `app.module.ts` to:

```ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ClientsModule, Transport } from '@nestjs/microservices';

@Module({
  imports: [
    ClientsModule.register([
      {
        name: 'kafka-client-test',
        transport: Transport.KAFKA,
        options: {
          client: {
            brokers: ['localhost:9092', 'kafka:29092'],
          },
          producer: {
            allowAutoTopicCreation: true,
          },
          producerOnlyMode: true,
        },
      },
    ]),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

and my `main.ts` to:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

I get the expected behavior and a consumer group isn't started in the logs. 

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

_No response_

### Packages versions

[System Information]
OS Version     : macOS Monterey
NodeJS Version : v18.13.0
NPM Version    : 8.19.3

[Nest CLI]
Nest CLI Version : 10.1.11

[Nest Platform Information]
platform-express version : 10.1.3
microservices version    : 10.1.3
schematics version       : 10.0.2
testing version          : 10.1.3
common version           : 10.1.3
core version             : 10.1.3
cli version              : 10.1.11

### Node.js version

18.13

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

In the [ClientKafka](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts#L120), there's logic around the `producerOnlyMode` when connecting to Kafka. But if you look in [ServerKafka](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-kafka.ts#L99), there's no logic here in `start` that refers to the `producerOnlyMode` property, even though it's a valid configuration option.

### PR DESCRIPTION
**Pull request by bylethviva**
Previously ServerKafka would accept, but not respect the producerOnlyMode configuration option. This updates the constructor and start method to use this flag to not start a consumer when in producer mode only. It also adds tests for the start method.

closes #12206

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [12206](https://github.com/nestjs/nest/issues/12206)

When starting the hybrid application, the startup logs show that a consumer has been started and that it has joined the consumer group with id nestjs-group-server.

## What is the new behavior?

These changes should prevent a consumer from starting up if the `producerOnlyMode` configuration option is set to true.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
BTW out of curiosity, why would you start Kafka sever that isn't capable of consuming messages?

**Comment by kamilmysliwiec** [comment]
@bylethviva so if it only produces messages, why do you need a server? You shouldn't use `createMicroservice` in the first place in this case - you can use `createApplicationContext` instead

**Comment by bylethviva** [comment]
How would `createApplicationContext` get me what I need in this case? I still need to connect to Kafka and produce the message. I don't see how the method you suggested will get me what I'm looking for here. We've got a hybrid application that accepts HTTP requests and needs to produce messages to Kafka in certain cases.

**Comment by kamilmysliwiec** [comment]
> I still need to connect to Kafka and produce the message.

You don't need `createMicroservice` for this. Just create a client (producer) https://docs.nestjs.com/microservices/kafka#client

**Comment by kamilmysliwiec** [comment]
We'd need a minimum reproduction repository to help

**Comment by bylethviva** [comment]
[Here's a repo](https://github.com/bylethviva/nestjs-clientsmodule-eventpattern-issues) that reproduces the issue. `main` uses `ClientsModule` and is unable to consume the emitted message in the `app.e2e-spec` test. On the other hand the [`refactor-to-connect-microservice` branch](https://github.com/bylethviva/nestjs-clientsmodule-eventpattern-issues/tree/refactor-to-connect-microservice) works as expected and I can consume the emitted message in the e2e test using the same mock controller that uses the `EventPattern` decorator.

**Comment by kamilmysliwiec** [comment]
I just looked through the codebase and it doesn't seem to be properly setup. On the main branch, why would you expect `MockConsumerController.DATA` to be updated if you only have a producer in your code (no server)? It works on the `refactor-to-connect-microservice` branch because `connectMicroservice` converts your application to a hybrid app (HTTP + microservice transporter aka server). While the terminology might be confusing, `ClientsModule` doesn't mean you create a consumer - instead, it provides you with an interface to **produce** messages/events (dispatch/emit). To consume messages, you need a server (`createMicroservice`).

**Comment by bylethviva** [comment]
On the main branch I would expect to be able to consume messages, in the e2e test, due to the fact that the `connect` method in `ClientKafka` configures a [consumer](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-kafka.ts#L139), provided that `producerOnlyMode` isn't set. 

> To consume messages, you need a server (createMicroservice).

Based on the code, I'd disagree with this statement. You can consume messages using `ClientKafka`, but you need to register the patterns via the use of `ClientKafka.prototype.subscribeToResponseOf` and the `MessagePattern` decorator as demonstrated [here](https://docs.nestjs.com/microservices/kafka#message-response-subscription). Why is there a difference between how `ServerKafka` and `ClientKafka` behave? `ServerKafka` will automatically listen for events that meet the patterns passed into `EventPattern` decorators.

> `ClientsModule` doesn't mean you create a consumer 

I'd also disagree with this. If you don't pass in `producerOnlyMode` when using `ClientsModule.register`, you will definitely start a consumer when you call `client.connect`. e.g. in the main branch of the repo I provided earlier, if you comment out [this line](https://github.com/bylethviva/nestjs-clientsmodule-eventpattern-issues/blob/main/src/app.module.ts#L25C1-L25C80), you should get something similar to the output in the screenshot below. There are lines stating that a consumer has started and that a consumer group has been joined. 

Screenshot 2023-08-16 at 1 26 30 PM

**Comment by kamilmysliwiec** [comment]
Ehhh

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Pull request closed without merging**
