### PR TITLE
fix(core): middleware is not executed for root route when global prefix is set

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/11572

## What is the new behavior?

Based off https://github.com/nestjs/nest/pull/12179

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by B4nan** [comment]
I'll have to check this myself, but I already heard from two of our users that this is not fixing the actual problem, at least not for the MikroORM integration.

**Comment by B4nan** [comment]
I'll have to check this myself, but I already heard from two of our users that this is not fixing the actual problem, at least not for the MikroORM integration.

**Comment by eric-deeporigin** [comment]
This is still not working for our apps even with latest version of nest (10.3.8), particularly with the MikroORM integration

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimum reproduction repository @eric-deeporigin?

**Comment by renanz** [comment]
> Could you please provide a minimum reproduction repository @eric-deeporigin?

@kamilmysliwiec  https://github.com/nestjs/nest/issues/13401#issuecomment-2174605844

**Pull request merged**
