### PR TITLE
feat(common): built-in, console logger refactor

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

https://github.com/nestjs/nest/issues/6142
https://github.com/nestjs/nest/issues/6172
https://github.com/nestjs/nest/issues/5353

and a few others.

## What is the new behavior?

- general refactor, separate out `Logger` wrapper class and `ConsoleLogger` class
- add buffering logs feature (buffer init logs and flush them out when a custom logger is assigned)
- add log level output https://github.com/nestjs/nest/issues/6172
- properly support log levels feature https://github.com/nestjs/docs.nestjs.com/issues/1613

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Review by jmcdo29 — COMMENTED** [review]
Wow! This is going to be incredibly helpful to so many! Quick question about what would happen, I think I know, but want to make sure,

Say that I want to use my custom logger, so I set `bufferLogs` to true and will call `app.useLogger(customLoggerInstance)` later on. If there is an error, such as Nest not being able to resolve a dependency, because `app.useLogger` hasn't been called yet, it will use Nest's default `ConsoleLogger` to print the error, correct?

**Comment by kamilmysliwiec** [comment]
> Say that I want to use my custom logger, so I set bufferLogs to true and will call app.useLogger(customLoggerInstance) later on. If there is an error, such as Nest not being able to resolve a dependency, because app.useLogger hasn't been called yet, it will use Nest's default ConsoleLogger to print the error, correct?

Correct :)

**Comment by WonderPanda** [comment]
Late to the party but thanks for these improvements @kamilmysliwiec! This looks badass

**Comment by jjchiw** [comment]
Hi

I don't know if it's related to this `PR`, but when we upgraded to `nestjs 8` all the tests that uses`Test.createTestingModule({` failed with this error `Error: Using the "extends Logger" instruction is not allowed in Nest v8. Please, use "extends ConsoleLogger" instead.`

We fixed the tests adding `setLogger(new ConsoleLogger()`

```
Test.createTestingModule({
    ...
  }).setLogger(new ConsoleLogger())
    .compile();
 ```

thanks :)

**Comment by jmcdo29** [comment]
@jjchiw make sure you're using `@nestjs/testing@^8`. V7 would still be using the old `Logger` class and will result in that error

**Pull request merged**
