### PR TITLE
feat(common): adds Locked exception with status code 423

### PR DESCRIPTION
**Pull request by AaronPerezPerez**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

We were lacking an exception for 423 Locked error.

## What is the new behavior?
Now we have it.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
hey! please read the comments on PR #9315

**Comment by AaronPerezPerez** [comment]
> hey! please read the comments on PR #9315
@[micalevisk](https://github.com/micalevisk) I can't find on the issues why they don't want to extend the enum, do you know why? (just curiosity)

**Comment by micalevisk** [comment]
I don't but I think it's to avoid increasing the code of `@nestjs/common` package. Otherwise we would need to support more and more status codes. So they choose only the most common ones.

**Comment by AaronPerezPerez** [comment]
Cool, thanks!

**Pull request closed without merging**
