### PR TITLE
chore(sample): Added sample for event emitter with nestjs

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, Added sample for event emitter with nestjs

### CODE REVIEW

**Comment by Tony133** [comment]
To evaluate the implementation if it is correct as I'm not sure enough :-)

**Comment by davidmaceachern** [comment]
Hi @Tony133, 

Thanks for adding this example it was very helpful.

I added some unit tests in my project if you want to add them to your example you can find them in the following places:

- [ ] [Testing the event class](https://github.com/davidmaceachern/consents-api/blob/master/consents/src/users/consent-user-deleted.event.spec.ts)
- [ ] [Stubbing the call to the event emitter so it doesn't actually emit an event](https://github.com/davidmaceachern/consents-api/blob/master/consents/src/users/users.service.spec.ts#L90)
- [ ] [Checking the event emitter is called](https://github.com/davidmaceachern/consents-api/blob/master/consents/src/users/users.service.spec.ts#L232).

**Comment by Tony133** [comment]
Hi @davidmaceachern,

I'm happy that the example can be useful, it means that my efforts to contribute to NestJS ♥️ are useful to people and that makes me very happy and proud to have done so.

Thank you very much for sharing the evidence too, I can be very helpful. 👍

**Comment by kamilmysliwiec** [comment]
There were a few changes needed to make it work (you can check them out here https://github.com/nestjs/nest/tree/master/sample/30-event-emitter), but otherwise, it looks good. Thanks!

**Pull request merged**
