### PR TITLE
feat: add prisma integration example

### PR DESCRIPTION
**Pull request by cschroeter**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Add example to demonstrate integration of [Prsima](https://www.prisma.io/)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Wow, looks very good at first glance. Could you use `@Args()`, `@Context()` etc instead? Also, let's update to latest patch version (without `test-types.graphql` bug)

**Comment by kamilmysliwiec** [comment]
> Not sure how to make use of those new decorators in the subscribe method though :/

it's impossible 😄

**Comment by kamilmysliwiec** [comment]
Look perfect @cschroeter!

**Comment by marcus-sa** [comment]
Maybe you could add some installation guide on how to actually integrate Prisma with Nest?
I suppose a sample is fine, but since Prisma is 3rd party, there might be some steps not mentioned in their docs to get it working with Nest.

Thanks a lot for the contribution though, just was I was looking for 💃

**Comment by marcus-sa** [comment]
Figured out I just had to run 
```sh
$ prisma deploy
$ graphql codegen
```

**Comment by agborkowski** [comment]
@cschroeter 🍻

**Comment by marcus-sa** [comment]
@agborkowski seems like there's duplicates of `src` files in the `root` directory

**Comment by cschroeter** [comment]
Yeah - my bad. I've created a new PR to address this issue .https://github.com/nestjs/nest/pull/1091

**Pull request merged**
