### PR TITLE
refactor(common): update log level

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/10878

## What is the new behavior?
- Updated the log level value
  
## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

 Note: PR for the next major version of NestJS 😻 (Not merge at the moment)

### CODE REVIEW

**Comment by Tony133** [comment]
In the old PR I had also moved the `ConsoleLoggerOptions` interface to a separate file, here I did not move it if you want I can move it otherwise it stays as it is now, for no problem. 👍

However I will check the files that are missing to add @ApiPublic so contributors like me have no problem figuring out which are public or private

**Review by andreyddk — APPROVED** [review]

**Comment by micalevisk** [comment]
since this introduces breaking changes (as per Kamil's comment), can you update that checkbox on PR's description? ~ just to clarify for future readers

I'll label this accordingly.

**Comment by Tony133** [comment]
Can we add it in this branch https://github.com/nestjs/nest/tree/10.0.0 ?

**Review by micalevisk — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
