### PR TITLE
[WIP] Feat/one

### PR DESCRIPTION
**Pull request by marcus-sa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

Introducing an entire new Nest that works everywhere, from browser, server to Electron.
New DI system using `Inversify`

```
[x] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[x] Other... Please describe:
```

## Issues fixed
https://github.com/nestjs/nest/issues/770
https://github.com/nestjs/nest/issues/1019
https://github.com/nestjs/nest/issues/1065
https://github.com/nestjs/nest/issues/531
https://github.com/nestjs/nest/issues/910
https://github.com/nestjs/nest/pull/1060

## What is the new behavior?
Tried to mostly have the same behavior, there's a lot of changes both for the good and the bad.
I'll do a breakdown of it all soon enough, once I've added the remaining tests and coded the migrations for all the server related stuff, then I'll update related docs in this PR, so everyone knows what the changes and additions are.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information
I will apply the commits from my original repository on top of this PR, so that it'll be easier to review.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Hi @marcus-sa,
Thanks for your effort. I know that this PR is still WIP, but I have to say one thing up front. It's very unlikely that this PR will be eventually merged and I'm not sure if you should spend too much time on it. I really appreciate your work and I believe that the code quality is very good. However, it's not a normal pull request, it's just a completely new framework with most of the codebase changed and rewritten core features with the same API. I know that it solves a few small issues (like platforms separation) but I'm certainly sure that we are able to achieve these goals with very little steps anyway without removing 3/4 code done so far. Nest is being used across a lot of production applications already and there is no particular reason to completely rewrite most of the code which works well and is stable for a huge set of solutions. I think that this is understandable from the perspective of the product that Nest has become, which in the eyes of people is above all to remain stable and trustworthy. I hope you'll understand my concerns. 🙁

**Comment by marcus-sa** [comment]
Totally understandable, just thought it'd be better to create a PR, than creating an entire new framework (as I've done) for exactly the same purpose :)

**Comment by marcus-sa** [comment]
Anyway as you've mentioned several times, the server stuff should be obsolete from the core framework to provide extensibility.
Maybe the core features are changed and have a lot of extra features, but isn't that the point?
Don't create a new framework, instead you should contribute to an existing. 
Whether or not my PR contains completely rewritten code or not, that doesn't matter. 
There's plenty of modules that could be created with the core DI system that would be useful. 
Everything is gonna be the same for the server related stuff (as discussed) controllers would just be instantiated through a feature module and guards, interceptors and pipes would be separate modules, so that they can be used through the websocket and microservice packages.
I'll write a breakdown of the additional features, what has changed API related and so on.

**Comment by marcus-sa** [comment]
* Only caveat is that Inversify can't resolve async factories before injecting, you'd have to do it manually, which is fine, because you can do the async instantiation with `APP_INIT` and `MODULE_INIT` tokens which the framework executes at app and module initialization

**Comment by kamilmysliwiec** [comment]
I believe that achieving all these goals discussed in the issues shouldn't require more than a few files changed, instead of the whole framework :)

**Comment by marcus-sa** [comment]
The only thing that has changed is that it's an independent DI framework as discussed it should be.
It's just using Inversify for more extensibility over your Nests own DI.

**Comment by BrunnerLivio** [comment]
I agree with @marcus-sa arguments. I’d actually prefer using Inversify, if it would fit our requirements. But this PR is too big. It would be too dangerous to merge in my opinion. But I think we could adapt some points from this PR. But one feature at the time...

**Comment by kamilmysliwiec** [comment]
One note: what we will certainly never do is switching to another DI system.

**Comment by kamilmysliwiec** [comment]
Anyway, as @BrunnerLivio said, one feature at the time which really solve one particular issue/provide a new functionality would be good. Nevertheless, I admire your job @marcus-sa, you put a lot of stuff and time in this repo. Very well!

**Pull request closed without merging**
