### PR TITLE
Update: release v5.0.0-beta

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
- [x] Increase coherence between Nest and Angular syntax
   - [x] Switch from `@Component()`, `@Middleware()`, `@Interceptor()`, and `@Guard()` to `@Injectable()` (deprecate old decorators)
   - [x] Switch from `components: []` to `providers: []` (deprecate old property)
   - [x] Deprecate `modules: []` property (use `imports: []` instead)
   - [x] Allow binding global interceptors, filters, pipes, and guards from any module.
Example:
```typescript
{
  provide: APP_INTERCEPTOR,
  useClass: LoggerInterceptor,
}
```
- [x] HTTP server independence
   - [x] Wrap `express` in `ExpressAdapter` and use it as a default HTTP provider
   - [x] Provide `FastifyAdapter` - [fastify](https://github.com/fastify/fastify) integration
   - [x] Independence means that Nest can make use of any library that provides a similar request-response cycle as express. Thanks to that, Nest could be used with such libraries like, for example, fastify, polka, or connect.
- [x] Move from traditional express middleware model, meaning, each middleware is solely bounded to a particular path, regardless of the request method. Also, there'll be no more error middlewares. This change helps us finding a middle-ground between throughput and express compatibility.
- [x] `@UseGuards()`, `@UsePipes()`, `@UseFilters()`, and `@UseInterceptors()` should **extend** metadata, instead of overriding existing one
- [x] Development experience
   - [x] Remove static dependencies that results in compatibility with HMR webpack (even 300% faster rebuilds)
- [x] Make microservices module far more robust
  - [x] Improve existing transport strategies (concurency, reconnecting strategies)
  - [x] Create new strategies - NATS, MQTT, and GRPC
- [x] Upgrade to latest RxJS (pipeable operators)
- [ ] Tooling (cc @ThomRick)
   - [ ] Switch to CLI as a recommended way to play with the framework
   - [ ] Schematics
- [x] Improve examples, documentation, and 3rd party modules
- [x] Improve typings (better UX)
- [x] Several other fixes and improvements

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
Amazing 🎉🎉 pls pls pls use this opportunity of a new major version bump to document the new system more detailed 🙂

**Comment by wbhob** [comment]
I’m happy to help write some docs.

**Comment by shekohex** [comment]
me too, Consider me In.

**Comment by wbhob** [comment]
I know I talked to @kamilmysliwiec about using the material docs. I don't know if your opinion changed, but using Markdown for the docs site would make it a lot easier to contribute.

**Comment by kamilmysliwiec** [comment]
Nest v5.0.0-beta.0 has been published with `@beta` tag. Feel free to play with it, I'd very appreciate each reported issue 🔥 🥇 

Here's a v5 documentation:
https://docs.nestjs.com/v5/

**Comment by avatsaev** [comment]
Great news! Is there a migration guide somewhere?

**Comment by ith** [comment]
@avatsaev https://docs.nestjs.com/v5/migration-guide

**Comment by thaoula** [comment]
Hi @kamilmysliwiec,

Awesome framework!!! We are currently building an application with V4 of the framework and I have started migrating to V5 beta 2.

Where would you like to us log the following issues?

1. The migration steps do not talk about using ExpressAdapter. This is needed when passing express instance.
2. The Express Adapter does not seem to be exported by @nestjs/core ... you have to do this 
import { ExpressAdapter } from '@nestjs/core/adapters/express-adapter';
3. Do we need to install Fastify? I am getting this error on all apps - 
Error: Cannot find module 'fastify-formbody'

I am happy to log seperate issue for each. Just not sure how you are handling v5.

Regards,
Tarek

**Comment by kamilmysliwiec** [comment]
Hi @thaoula,
Thanks! Feel free to create a single issue with them 🙂

**Comment by thaoula** [comment]
Hi @kamilmysliwiec,

Done, can be found here - https://github.com/nestjs/nest/issues/575

Regards,
Tarek

**Pull request merged**
