### PR TITLE
feature(core): allow status override in interceptors

### PR DESCRIPTION
**Pull request by ToonvanStrijp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently the only way to set a custom http status code is to use the @Res() or @HttpCode(). By default Nest is returning 200 or 201. Right now I'm trying to implement a interceptor that sets the status code but because Nest is overriding this in the reply phase it's not possible to set it. Or yeah it is but Nest overrides it.

Issue Number: #1869

## What is the new behavior?
I've replaces the code where nest is setting the HttpStatus, this way the status is set before nest is running trough all the interceptors. Because of this we now can override the status by doing `res.status(404)` or we could read the current status by doing: `res.statusCode`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
What about setting `status` conditionally inside the `reply()` method (and making `statusCode` argument optional)? That would allow moving forward with this enhancement without breaking API, tests, exception filter changes, etc.

**Comment by ToonvanStrijp** [comment]
One other proposal I've in mind is to move the setHeaders inside the `router-execution-context.ts` to the same place where I added the http status code. This way we also can override headers inside interceptors.

Right now nest is overriding the headers set by `res.header()` so this way you won't be able to adjust certain headers inside your interceptor.

Let me know if it looks good and what changes are needed.

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec we could do that, but since It's hard to measure when we need to set it conditionally. And if an interceptor wants to read the current status it possible by doing it my way.

Also if `express` or `fastify` changes their default response then the condition check won't work properly anymore. But setting it up front we make more things possible.

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec we could do that, but since It's hard to measure when we need to set it conditionally. 

Your current solution is fine. I'm just saying that you can leave `reply` signature as before (with `statusCode`) and make status optional. Then, simply check `if (statusCode)` :) Thus, you won't be forced to perform any changes in tests, exception filters, and the API would remain the same. The rest is great :D

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec ahh like that ;) Of course  will change it in a minute. One other thing what we could improve is also set the headers before running the interceptors?

**Comment by kamilmysliwiec** [comment]
So I assume that you basically want to give an ability to override headers set through `@Header()` decorator inside the interceptor?

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec yes exactly ;), let me know if we want that, then I'll create a new pull request with this feature in it.

**Comment by kamilmysliwiec** [comment]
Well, why not :) Sounds good!

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec alright I've reverted the code so that the signature of reply didn't change only made the statusCode optional and check for it in the reply. Let me know if any other changes are needed.

Also should I change the header feature in this pull request? Otherwise we get merge conflicts later on.

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec is there any documentation that needs to be changes?

**Comment by kamilmysliwiec** [comment]
> Also should I change the header feature in this pull request? Otherwise we get merge conflicts later on.

You can push headers feature here too.

> @kamilmysliwiec is there any documentation that needs to be changes?

Very likely no :)

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec any idea why the test fails?

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec I think there is something wrong with the travis config, cause at my pc it's running fine and all the tests pass. But somehow node 8 has troubles with typeorm?

**Comment by kamilmysliwiec** [comment]
There is a sort of race condition that I have to fix shortly. No worries (triggering another build should help)

**Comment by ToonvanStrijp** [comment]
@kamilmysliwiec how do I trigger an other build? :)

**Comment by kamilmysliwiec** [comment]
No worries, I'll fix that! Great contribution, thanks @ToonvanStrijp :)

**Pull request merged**
