### PR TITLE
call serializeError for grpc client

### PR DESCRIPTION
**Pull request by DenisVASI9**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[* ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
I add a serializeError call from a super class, 
to be able to create a custom proxy in which I can overload serializeError.

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ *] No
```

## Other information

### CODE REVIEW

**Comment by jmcdo29** [comment]
We may want to allow for serialization of the errors for the stream service method (line 182) and the unary service method that is stream-like (line 224). I think that's my only concern to make sure they're all handled the same way. @kamilmysliwiec do you have any thoughts on it?

**Comment by kamilmysliwiec** [comment]
Sounds good @jmcdo29! @DenisVASI9 can you add this to the PR?

**Comment by DenisVASI9** [comment]
@kamilmysliwiec Ok, I'll do it

**Comment by DenisVASI9** [comment]
@kamilmysliwiec I sent it, please take a look at it

**Comment by kamilmysliwiec** [comment]
Could you rebase this PR & resolve conflicts? :)

**Comment by DenisVASI9** [comment]
@kamilmysliwiec Ok

**Comment by kamilmysliwiec** [comment]
🏓

**Pull request closed without merging**
