### PR TITLE
feat(@nestjs/common): Added parser UUID pipe

### PR DESCRIPTION
**Pull request by gperdomor**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Nest include a pipe to parse integers but none to parse UUID, it is common to have resources with UUID as an identifier

Issue Number: N/A

## What is the new behavior?
This PR adds a new UUID pipe, useful to parse route parameters when we are working with resources with UUID as identifier

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Great idea! This probably doesn't make sense to include another required dependency (`validator` package) just for the sake of a single function. I'd suggest moving `isUUID` logic to the pipe itself:
https://github.com/chriso/validator.js/blob/master/lib/isUUID.js

**Comment by gperdomor** [comment]
the `validator` package is a dependency of `class-validator` which actually is used by the `ValidatorPipe`, so really is not a new dependency because is already installed with the `class-validator` 🤔...

In fact the validation can be archived through the `class-validator` package like this:


```typescript
import {Validator} from "class-validator";

// Validation methods
const validator = new Validator();
validator.isUUID(str, version);
```

**Comment by kamilmysliwiec** [comment]
`class-validator` is not a required package as well (see `ValidationPipe` implementation)

**Comment by kamilmysliwiec** [comment]
ping 🏓

**Comment by gperdomor** [comment]
@kamilmysliwiec updated :D

**Comment by gperdomor** [comment]
ping @kamilmysliwiec

**Comment by SeWaS** [comment]
Just an idea: does it make sense to you to include a kind of an `exceptionFactory` (similar to the `ValidationPipe`-implementation)? I think it would be great to have the possibility to customise the exception that is thrown.

**Comment by kamilmysliwiec** [comment]
It would be great @SeWaS :) @gperdomor would you be interested in adding this feature?

**Comment by SeWaS** [comment]
Looks good to me. Thank you very much for adding 😎

**Comment by kamilmysliwiec** [comment]
Perfect. Would you be interested in creating a PR to the docs with this feature?

**Comment by gperdomor** [comment]
@kamilmysliwiec https://github.com/nestjs/docs.nestjs.com/pull/446

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
