### PR TITLE
[WIP] doc(samples) update samples

### PR DESCRIPTION
**Pull request by johnbiundo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Samples have been updated as follows:

- all now use the current npm scripts from `typescript-starter`
- added `prestart:prod` script to avoid unnecessary error for new users
- all sample apps now listen on port 3000 (some listened on 3001)
- all relevant code now references `AppModule` instead of `ApplicationModule` for consistency with CLI and documentation
- apps that need Docker to run have a small README showing how to use Docker (or local instance of the DB)

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Thanks @johnbiundo! Is this PR ready for review? :)

**Comment by johnbiundo** [comment]
Sorry, no, I found some changes I need to make.  Updating title.

**Comment by johnbiundo** [comment]
@kamilmysliwiec I have a few things to clean up on this.  But should I wait for https://github.com/nestjs/typescript-starter/pull/151/commits/713503855c4a029b38f99b7c049cefb13f34fa6e and just do the switch over to the CLI scripts? Or would you rather do that separately?  (This PR cleans up a few other things, including a few READMEs, `ApplicationModule` -> `AppModule`, etc)

**Comment by kamilmysliwiec** [comment]
Good catch @johnbiundo! Let's update all scripts to the new CLI scripts :)

**Comment by kamilmysliwiec** [comment]
Since CLI features have been merged, this PR is a priority now. @johnbiundo if you are busy now, I can finish the rest (update scripts etc)

**Comment by johnbiundo** [comment]
Here's the current status and open questions/issues:

1. All samples now use `AppModule` instead of `ApplicationModule`
2. All samples now use the current scripts from `typescript-sample`
3. All samples now listen on port 3000 (some listened on 3001)
4. Samples that use docker have a small readme to explain how to use them
5. 19-auth-jwt addresses https://github.com/nestjs/docs.nestjs.com/issues/708
6. **OPEN** scripts still use `prebuild` with `rimraf`, not the new CLI option to `deleteOutDir`.  Also, `rimraf` is still a `dependency`, not a `dev-dependency`.  Need to resolve both.
7. **OPEN** sample-22 does not compile properly.  Could use @kamilmysliwiec help to resolve.
8. **OPEN** sample-08 and sample-09 are compiler examples, so I did not change the scripts.  Need @kamilmysliwiec to look at those.
9. **OPEN** @kamilmysliwiec please take a look at the `README.md` in `01-cats`.  What do you think of that -- should we add to each?
10. **OPEN** @kamilmysliwiec can you guide me on taking care of the conflicting package-lock.json file for sample 23?

**Comment by BrunnerLivio** [comment]
Nice work, well done @johnbiundo !
How about we also add tests to the samples? This would leverage our integration test (we could test in the pipeline the NestJS code against all samples) + examples would be improved. Off course this is quite a time-consuming task, but since it is currently Hacktoberfest it would be a nice time for users to contribute on an easy level :)

**Comment by johnbiundo** [comment]
@BrunnerLivio Love that idea!  Can we get visibility to that task (writing tests)?

**Comment by kamilmysliwiec** [comment]
Resolved conflicts & pushed a few updates.

> OPEN scripts still use prebuild with rimraf, not the new CLI option to deleteOutDir. Also, rimraf is still a dependency, not a dev-dependency. Need to resolve both.
 
Let's stay consistent with the starter project for now. Once we decide to move away from `rimraf`, we'll update samples accordingly.

> OPEN sample-08 and sample-09 are compiler examples, so I did not change the scripts. Need @kamilmysliwiec to look at those.

Done 

> OPEN @kamilmysliwiec please take a look at the README.md in 01-cats. What do you think of that -- should we add to each?

It would be useful, but we can't rely on some random package in this case.

> OPEN @kamilmysliwiec can you guide me on taking care of the conflicting package-lock.json file for sample 23?

Done

**Comment by kamilmysliwiec** [comment]
Thanks :)

**Pull request merged**
