### PR TITLE
refactor(): improvements the imports

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Proposals:

Improvements to imports in the following files:
  - `packages/core/helpers/external-context-creator.ts`
  - `packages/core/router/router-explorer.ts`
  - `packages/core/scanner.ts`
  - `packages/testing/testing-module.builder.ts`
  - `packages/websockets/context/ws-context-creator.ts`

Removed type not used in the following file (see screenshot):
  - `packages/core/middleware/routes-mapper.ts`

Screenshot 2023-01-12 alle 17 07 48

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by Tony133** [comment]
very strange is not related to the changes in this PR 🤔:

Screenshot 2023-01-16 alle 16 23 33

**Comment by Tony133** [comment]
CI passed ✅  🙌

**Comment by kamilmysliwiec** [comment]
Apologies for not reviewing this PR sooner. Could you resolve conflicts?

**Comment by micalevisk** [comment]
@kamilmysliwiec I believe this introduces a regression :crying_cat_face: 

image

in my project a didn't have `class-validator` installed because I don't use any of `class-validator`-related features that comes with `@nestjs/common`

but since I imported `@nestjs/common`, nodejs ends up evaluating the following line, which leads to the above error

https://github.com/nestjs/nest/blob/0a4f9419d8f963e397f7150896558cb37403a3d8/packages/common/pipes/file/parse-file.pipe.ts#L7

**Comment by kamilmysliwiec** [comment]
Well, there should be no direct imports from the "class-validator" in the first place 😄 Let me fix this up

Side note - we might need to stop accepting the "imports refactor" PRs, they don't bring much value anyway

**Comment by Tony133** [comment]
in this PR, however, I have not touched class-validator

**Comment by kamilmysliwiec** [comment]
Yeah it's related to another PR - https://github.com/nestjs/nest/commit/7792c43b93c7617601208e894632c6d0090fced0

**Comment by Tony133** [comment]
Ok in fact I said it was strange, I'm usually very careful about these things. 

@micalevisk you can move your message into that PR so we know it's the one that created the regression.

**Pull request merged**
