### PR TITLE
refactor(fastify): update fastify static options interface

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Proposal:

- Refactor `fastify-static-options.interface.ts`, see here for other info: https://github.com/fastify/fastify-static/blob/master/types/index.d.ts

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Was it added in the latest version (that is not yet compatible with Nest)?

**Comment by Tony133** [comment]
> Was it added in the latest version (that is not yet compatible with Nest)?

With the new version of Fastify 5.x, a small change has been made to the interface, see here : https://github.com/fastify/fastify-static/commit/426f3be25a866376a4a8beb858005a0063704c0e#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceL80
The version of the `@fastify/static` package released for Fastify 5.x and `v8.0.0`, is now `v8.0.2`

**Comment by kamilmysliwiec** [comment]
So if that's the case, shouldn't we target the 11.0.0 branch instead of master?

**Comment by Tony133** [comment]
> So if that's the case, shouldn't we target the 11.0.0 branch instead of master?

I think we can also merge it into v10.x only that that small change was made in the new version of the `@fastify/static` v8.0.0 package which is only compatible with fastify v5.x, at best I can remove it and make a separate PR with that small change.

**Pull request merged**
