### PR TITLE
feat(microservices) add capability to use RegExp in Kafka Events

### PR DESCRIPTION
**Pull request by alfredoperez**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The @EventPattern() and @MessagePattern() only takes strings to match the events for Kafka.

Issue Number: 3083

## What is the new behavior?
Now it will be possible to have a Regular Expression to match event and message

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
I'm not entirely sure if that's a good idea to add custom features on top of the transport strategy. The kafka library should support such a functionality out-of-the-box.

**Comment by ruscon** [comment]
@kamilmysliwiec 
`kafkajs` supports regex
You can check this
https://github.com/tulios/kafkajs/blob/6cd8c988852ceb08a43c698c23ea34f9a760906a/src/consumer/__tests__/subscribe.spec.js#L57

Or did you mean something else?

**Comment by inhyeok** [comment]
@kamilmysliwiec 
When can I use this feature?

**Comment by kamilmysliwiec** [comment]
`kafkajs` supports Regexp, but this PR doesn't leverage that but rather tries to match every incoming message pattern https://github.com/nestjs/nest/pull/3167/files#diff-ba32d4569e323f15018277fe42c660c5b972b0ab08aadf24e6f286853edf32a3R69-R72 I'd be more than happy to see a PR that integrates `kafkajs` regular expressions support though

**Comment by fjodor-rybakov** [comment]
@kamilmysliwiec i think this pr need to be reviewed. Regular expressions will only work if you [rewrite logic](https://github.com/tulios/kafkajs/blob/master/src/consumer/index.js#L165) from `kafkajs` to `ServerKafka` or do same as author did in this pr

**Pull request closed without merging**
