### PR TITLE
feat(@nestjs/core): Add init function on NestApplicationContext to API

### PR DESCRIPTION
**Pull request by BrunnerLivio**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

`init` function is not exposed on `NestApplicationContext` 
Issue Number: #1592 

## What is the new behavior?

Exposed `init` function on `NestApplicationContext`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Have you checked the compatibility with other interfaces (application and microservice)? I'm pretty sure that `init()` is being there as well + these interfaces extend `INestApplicationContext`

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec I looked closer into it again and I think it is kinda hard to fulfill the all expected behaviors, mostly because as far as I know `NestApplication`, `NestApplicationContext` and `NestMicroservice`-classes do not have any unit tests? So before I mess things up I'd prefer to either 

- (rebase to 6.0.0-next and) add some unit test cases, then create an additional PR with the new `init` changes
- You add this functionality yourself since you're the expert and know what areas could be affected

**Comment by kamilmysliwiec** [comment]
It will be published as 6.3.0

**Comment by dls314** [comment]
I'm (re|mis)using nest through just the application context as a DI container for some AWS Lambdas where it's handy to have the same providers and other DI structure, but I'm not using any of the platforms.

Now that there is an init on the application context, should I call it when I'm just using it as DI container?

**Pull request merged**
