### PR TITLE
fix: bumps express and body-parser to their latest versions

### PR DESCRIPTION
**Pull request by bu-michael**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Fixes https://github.com/nestjs/nest/issues/13960 and https://github.com/nestjs/nest/issues/13959 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Fix security vulnerabilities

## What is the current behavior?

* https://github.com/nestjs/nest/issues/13960
* https://github.com/nestjs/nest/issues/13959 

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by Kenzo-Wada** [comment]
When will this PR be merged?? looking forward....:heart:

**Comment by thomashohn** [comment]
@bu-michael Could you bump express to 4.21.0?

**Comment by bu-michael** [comment]
> @bu-michael Could you bump express to 4.21.0?

For sure

**Comment by LucasGabrielBecker** [comment]
+1 waiting for this

**Comment by brunoventurazup** [comment]
+1 waiting for this

**Comment by bu-michael** [comment]
@thomashohn Bumped express to 4.21.0

**Comment by thomashohn** [comment]
@bu-michael - nice - unfortunately I'm no maintainer of this repo - but would like have have it merged ASAP too :)

**Comment by kamilmysliwiec** [comment]
Fixed in https://github.com/nestjs/nest/pull/13971

**Pull request closed without merging**
