### PR TITLE
feat(common): specify Error as default type parameter of ExceptionFilter

### PR DESCRIPTION
**Pull request by JeukHwang**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
Use any as the default type parameter

## What is the new behavior?
Use Error as the default type parameter

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by micalevisk — COMMENTED** [review]
I don't think that we should default to `Error` because anything can be caught by a filter

for example, `throw "my-error"` will be caught by a catch-all exception filter

**Comment by JeukHwang** [comment]
However, isn't ExceptionFilter obvious(easy-to-understand) to catch Errors?
Users can still change the type parameter as they want while the default type parameter coverage lots of use-cases.

**Comment by JeukHwang** [comment]
> > However, isn't it obvious that ExceptionFilter catch Error?
> 
> nop, it is supposed to catch _exceptions_, not errors.
> 
> In js, an exception can be anything.

I understand, but as I know (according to lots of websites, and tutorials), lots of users use `ExceptionFilter` for catching Error.

The possible  type can be highlighted as `T=Error extends any`

**Comment by JeukHwang** [comment]
> > However, isn't it obvious that ExceptionFilter catch Error?
> 
> nop, it is supposed to catch _exceptions_, not errors.
> 
> In js, an exception can be anything.

Could you provide a reliable source that talks about the difference between `Exception` and `Error`?
I want to read more materials about its definition.

**Comment by micalevisk** [comment]
I don't recall any

but I'm talking about what you can do in JS, not about concepts. If you're saying that `T` is `Error` by default, you'll end up misleading users because nesjts won't prevent them to use the filter for non-error objects. It's up to know the differences between `throw new Error` and `throw 'error'`.

**Comment by JeukHwang** [comment]
> I don't recall any
> 
> but I'm talking about what you can do in JS, not about concepts. If you're saying that `T` is `Error` by default, you'll end up misleading users because nesjts won't prevent them to use the filter for non-error objects. It's up to know the differences between `throw new Error` and `throw 'error'`.

Thanks for your reply. Have a nice day :)

**Pull request closed without merging**
