### PR TITLE
chore: typo fix

### PR DESCRIPTION
**Pull request by chunghha**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ x ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Just random typo fixes. Please review.

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [ x ] No

## Other information

### CODE REVIEW

**Review by micalevisk — APPROVED** [review]
I wonder how did you manage to find those typos

**Review by Tony133 — APPROVED** [review]
There are many modified files but still, great capture! 👍

**Comment by chunghha** [comment]
@micalevisk I use https://github.com/crate-ci/typos

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
