### PR TITLE
fix(core): middlewareConsumer forRoutes controller

### PR DESCRIPTION
**Pull request by Zclhlmgqzc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

```js
@Controller()
export class AppController {
  @Get('/')
  homepage(): string {
    return 'hit /';
  }

  @Get('/test/app')
  username(): string {
    return 'hit /test/app';
  }

  @Get('/:username')
  users(): string {
    return 'hit /:username';
  }
}
```
forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) === forRoutes(AppController)

Issue Number: #7737 #8108

## What is the new behavior?

forRoutes(AppController) should be equal to [{ path: '/$' }, { path: '/test/app$' }, { path: '/:username$' }]

forRoutes({ path: '/' }, { path: '/test/app' }, { path: '/:username' }) should be not equal to forRoutes(AppController)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by Zclhlmgqzc** [comment]
Maybe a bug

http://127.0.0.1:3001/test => hit path test

```
const express = require('express')()

express.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path test')
    }
})

express.use('*', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path /')
    }
})

express.listen(3001)
```
http://127.0.0.1:3001/test => hit path /

```
const express = require('express')()

express.use('*', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path /')
    }
})

express.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path test')
    }
})

express.listen(3001)
```

but

http://127.0.0.1:3002/test => hit path /

```
const Fastify = require('fastify');

async function main() {
  const fastify = Fastify()

  await fastify.register(require('middie'))

  fastify.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.end('hit path test')
    }
  })

  fastify.use('(.*)', function (req, res, next) {
    if (req.method === 'GET') {
        res.end('hit path /')
    }
  })

  fastify.listen(3002)
}

main()
```

**Comment by Zclhlmgqzc** [comment]
Maybe a bug

http://127.0.0.1:3001/test => hit path test

```
const express = require('express')()

express.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path test')
    }
})

express.use('*', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path /')
    }
})

express.listen(3001)
```
http://127.0.0.1:3001/test => hit path /

```
const express = require('express')()

express.use('*', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path /')
    }
})

express.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.send('hit path test')
    }
})

express.listen(3001)
```

but

http://127.0.0.1:3002/test => hit path /

```
const Fastify = require('fastify');

async function main() {
  const fastify = Fastify()

  await fastify.register(require('middie'))

  fastify.use('/test$', function (req, res, next) {
    if (req.method === 'GET') {
        res.end('hit path test')
    }
  })

  fastify.use('(.*)', function (req, res, next) {
    if (req.method === 'GET') {
        res.end('hit path /')
    }
  })

  fastify.listen(3002)
}

main()
```

**Comment by kamilmysliwiec** [comment]
Can we add an e2e test for this? Also, is this supported by fastify?

**Comment by Zclhlmgqzc** [comment]
> Can we add an e2e test for this? Also, is this supported by fastify?

I will add test as soon as possible
'($)' is supported by fastify
so use '($)' instead of '$'

**Comment by oleg-yudovich** [comment]
Hey @kamilmysliwiec. This bug is critical. We are not able to bump to NestJS 8 because of this issue. Any chance you will prioritize this fix. 🙏

**Comment by oleg-yudovich** [comment]
> > Hey @kamilmysliwiec. This bug is critical. We are not able to bump to NestJS 8 because of this issue. Any chance you will prioritize this fix. 🙏
> 
> Maybe you can try createApplyForController
> 
> ```js
> function createApplyForController(callback) {
>   return (req, res, next) => req.url === '/' ? callback(req, res, next) : next()
> }
> 
> @Module({})
> class AppModule implements NestModule {
>   configure(consumer: MiddlewareConsumer) {
>     consumer
>       .apply(createApplyForController((req, res) => res.send('hit path /')))
>       .forRoutes({ path: '/', method: RequestMethod.GET })
>       .apply(createApplyForController((req, res) => res.send('hit path /test/app')))
>       .forRoutes({ path: '/test/app', method: RequestMethod.GET })
>       .apply(createApplyForController((req, res) => res.send('hit path /:username')))
>       .forRoutes({ path: '/:username', method: RequestMethod.GET });
> 
>      // or Express Middleware
>      // .apply(createApplyForController(bodyParser.json()), createApplyForController(bodyParser.urlencoded({ extended: false })))
>      // .forRoutes(AppController)
>   }
> }
> ```

@Zclhlmgqzc thanks for the suggestion, but we have created a framework in my organization based on NestJS.
This framework is in use in many microservices. It is very undesirable to patch each microservice that decides to use the `/` route.  
I also hope this is the only issue in middleware consumer in NestJS 8

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
