### PR TITLE
refactor: Add MulterFile interface

### PR DESCRIPTION
**Pull request by BenWildeman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Created an interface for the file object for Multer so that it  can be imported into your nest project

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
> Created an interface for the file object for Multer so that it can be imported into your nest project

Shall this interface be exposed directly from `@nestjs/common`? If so, we'd have to add it to the `index.ts` file

**Comment by nartc** [comment]
`MulterFile` interface is pretty dynamic based on the storage that you use. I think this interface should be implemented at the project level, not at the library level. Below is an example of a file that's uploaded using Multer Cloudinary Storage:

```ts
export interface CloudinaryFile {
  fieldname: 'avatar';
  originalname: string;
  encoding: string;
  mimetype: 'image/jpeg' | 'image/png';
  public_id: string;
  version: number;
  signature: string;
  width: number;
  height: number;
  format: 'jpg' | 'png';
  resource_type: 'image';
  created_at: string;
  tags: string[];
  bytes: number;
  type: 'upload';
  etag: string;
  placeholder: boolean;
  url: string;
  secure_url: string;
  original_filename: 'file';
}
```

**Comment by BenWildeman** [comment]
@kamilmysliwiec yeah it could be.
@nartc as per the multer docs, it states that every file object contains what I specified which means if there's more that's included depending on the storage used as you've said, then you can just extend the base one and add the stuff that's missing, instead of having to manually create this interface in full

**Comment by kamilmysliwiec** [comment]
However, `multer` typings are intentionally located in `external` directory because they come from an external library. If one wants to use `MulterFile`, this one located in the original typings should be used. We put them inside the package just to provide better code autocompletion and IntelliSense.

**Comment by kamilmysliwiec** [comment]
So I personally think that we should avoid bringing another interface because that may lead to some weird auto-imports in developers IDEs. `MulterFile` interface located in the `@nestjs/platform-express` should never be used anyway (all these interfaces have been duplicated to provide better auto-completion and nothing else)

**Pull request closed without merging**
