### PR TITLE
[next] major 6.0.0 release

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: RC
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
- extract platforms #1329 
- simplify middleware API #1378 
- scopes (async-scoped DI, for example, per-request) #1376 
- events feature (microservices)
- simplify interceptor API (+fix order)
- simplify metadata API (`@SetMetadata`)
- no implicit `any`
- remove old deprecations
- lifecycle hooks #1416 

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by Tarjei400** [comment]
Good morning, I am not sure if its correct place to put it, maybe lets move it later on if you find it a bug.  I recently got 6.0.0-next branches for nest and nest/graphql it looks like if I create simple graphql resolver and inject a class using Scope.REQUEST apllication throws this error on execution. Propblem vanish when I use no options in Injectable decorator. but obviously injection strategy chesnges. I think it used to work when I created simple rest api. 
I thought its worth mentioning, have a great day!

Error: 
image

**Comment by kamilmysliwiec** [comment]
Hi @Tarjei400,
GraphQL package will be updated as well.

Btw, I just published the next version of docs 
https://docs.nestjs.com/v6/

**Comment by Tarjei400** [comment]
I noticed something wierd though after short debugging, might be helpful for you (unless you already have an idea whats wrong) 
in resolver-explorer.service (graphql module) we call this one :
`const wrapper = coreModuleRef.getProviderByKey(core_1.REQUEST);
`
and that returns undefined. 
However if you print coreModuleRef._providers there clearly is a key Symbol(REQUEST) 
So my guess is that there are 2 symbol objects created somehow. not sure yet though

Thank you for link to documentation! Keep up a great work!

**Comment by Tarjei400** [comment]
Hey just quick update, I pull latest changes. Probably I screwed up linking of packages -> my project had one version of fest, and graphql module had other. Either way Its seems to be good now. I will play a little bit more but I think its going to be fine now! Quick question - are you going to release alpha4 or are you preparing for a major release now?

**Comment by marcus-sa** [comment]
Been away a while due to moving to the UK and FedEx managing to destroy my PC completely.
Nice release, looking forward to it!

**Comment by kamilmysliwiec** [comment]
Docs: https://docs.nestjs.com/v6/
The new alpha version has been published if anybody wants to give a shot to the early access 😄 
`@6.0.0-alpha.4`

**Comment by Tarjei400** [comment]
@kamilmysliwiec when I injected request object in graphql module, object has only stacktrace, nothing related to express request object, like headers etc. Is that expected or something that needs to be updated in @nest/graphql package?

**Comment by siriushaha** [comment]
@kamilmysliwiec @nestjs/graphql"' has no exported member 'GraphQLDefinitionsFactory' for 6.0.0-alpha.3

**Comment by JeetChaudhari** [comment]
I tried @6.0.0-alpha.4 for sample 23-type-graphql, I am getting the following error.

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/d/Dev/jeet-chaudhari/nest/sample/23-type-graphql/node_modules/apollo-env/src/polyfills/array.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by imione** [comment]
My all appreciate for your effort.
Now my team is struggling to use DI because v5 does not support 'scopes'.
I am really looking forward to new v6 contains scoped providers.
Can I ask you when it is planned to be released?

**Comment by kamilmysliwiec** [comment]
Just published `@nestjs@6.0.0-rc.1`

**Comment by Tarjei400** [comment]
https://github.com/nestjs/graphql/issues/138

**Comment by johannesschobel** [comment]
Dear @kamilmysliwiec ,
wow, that is great news.. What is your expected release date for `6.0.0-stable`? 

All the best

**Comment by thaoula** [comment]
Do you have any documentation around the new features for v6?

**Comment by siriushaha** [comment]
https://docs.nestjs.com/v6

**Comment by Tarjei400** [comment]
Is someone here getting this problem with Scopes aswell, when using graphql? 
https://github.com/nestjs/graphql/issues/138

**Comment by gperdomor** [comment]
How can I create a new project using the 6.0.0 RC?

**Pull request merged**
