### PR TITLE
feat(common): added accept decorator

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, added accept decorator

### CODE REVIEW

**Comment by Tony133** [comment]
I just have some doubts about the implementation in fastify-adapter.ts, as not used much fastify and in router-response-controller.ts.

**Comment by kaznovac** [comment]
@Tony133 
please be aware that by default `@nestjs/platform-express` registers only these two body parsers
https://github.com/nestjs/nest/blob/3044e1555f04143800f0802262bec8af64d8f09e/packages/platform-express/adapters/express-adapter.ts#L135-L143

making `application/x-www-form-urlencoded` and `application/json` sole candidates for the `Accepts` header; unless developer opts-out from default platform bodyParsers and registers custom ones.

n.b. not sure about fastify either

**Comment by Tony133** [comment]
Hi, @kaznovac 

Thank you for reminding me.
by chance you have some idea how to disable it when there is an accept custom?

For Fastify I think it's the same, but it only defaults to one parser: application / x-www-form-urlencoded

```
  public registerParserMiddleware() {
    if (this._isParserRegistered) {
      return;
    }
    this.register(require('fastify-formbody'));
    this._isParserRegistered = true;
  }
```

**Comment by kaznovac** [comment]
passing the `bodyParser: false` parameter to `NestFactory.create` `options` will skip registering of the default body parsers
```
  const app = await NestFactory.create<NestExpressApplication>(
    AppModule,
    {
      bodyParser: false,
    },
  );
```

and than register the parsers you would like to use by `app.use` in the bootstrap process

**Comment by Tony133** [comment]
What file is this piece of code in?

**Comment by kamilmysliwiec** [comment]
This has been discussed in the past. We don't plan to add more decorators to simply wrap `Response` or `Request` objects methods. Thanks for your contribution though.

**Pull request closed without merging**
