### PR TITLE
Revert "fix(core): :ambulance: Fix for calculating durability of a provider"

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
Reverts nestjs/nest#11041

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Investigating if this PR might have accidentally caused some other regressions 🤔  
image

**Comment by kamilmysliwiec** [comment]
Sounds like that might be the case @vizio360 
image
(see that circular dependencies in the integration tests are now introspected as non-static even though they _are_ static)

**Comment by kamilmysliwiec** [comment]
It's a very edge-case scenario so no worries! Let me think how we can _easily_ fix this up

**Review by micalevisk — APPROVED** [review]

**Comment by vizio360** [comment]
> It's a very edge-case scenario so no worries! Let me think how we can _easily_ fix this up

@kamilmysliwiec oh ok, the never ending changes :) sorry about this guys. I could have a look after work today, unless you find a fix before then. We should also check if we can create a unit test for this.

**Comment by kamilmysliwiec** [comment]
This issue originates from this change, specifically - just to keep everyone in the loop

image

**Comment by kamilmysliwiec** [comment]
I have already tracked this down - will commit in a few mins

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/commit/6c99b704f69d0e5cec651bfcc150a0ed8ae08db8

**Comment by vizio360** [comment]
and the test I suggested seems to never end (I had a suspicion that it will infinitely run), so I need to figure out how to do the forwardRef.

**Pull request closed without merging**
