### PR TITLE
fix(integration): use the fastify adapter on integration fastify tests

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

there are `fastify.spec.ts` files that aren't using the `FastifyAdapter` when it was supposed to be

## What is the new behavior?

add missing calls to `new FastifyAdapter()`

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
@Sikora00 turns out there's something we missed in your Fastify CORS PR (https://github.com/nestjs/nest/pull/6144), see above ☝️  After adding the `FastifyAdapter`, tests started failing 

image

@tolgap likewise with the "Raw body" feature (and the PR we just recently merged in) 👀

**Comment by Sikora00** [comment]
I will check it @kamilmysliwiec 
One question, how did it turn out? If I go back to the state before my PR and I do this change will it work?

**Comment by tolgap** [comment]
@kamilmysliwiec @micalevisk Taking a look as well. Thanks for the headsup!

**Comment by Sikora00** [comment]
Ok, so I will check it

**Pull request closed without merging**
