### PR TITLE
fix added semi-colons

### PR DESCRIPTION
**Pull request by doriandevtech**
- [X] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jmcdo29** [comment]
Stop adding PRs like this. TRhey're not necessary

**Comment by doriandevtech** [comment]
Oh ok... I thought that respecting TS Prettier rules were mandatory... but it doesn't seems to be the case... sorry

**Comment by jmcdo29** [comment]
Prettier doesn't add semi-colons here.
image

**Comment by doriandevtech** [comment]
> Prettier doesn't add semi-colons here.
> image

You're right I also checked on my side and Prettier doesn't had anything

**Comment by doriandevtech** [comment]
I started to use NestJs a few days ago and I really like the construction and architecture that is behind it and I would like to contribute (because I want to learn and not only to have "green squares" 😂)

Do you have any advices in order to contribute in an effective way to this project (or derive projects linked to NestJS) ?

**Comment by jmcdo29** [comment]
[Have you checked our docs for learning NestJS?](https://docs.nestjs.com). Or [read the CONTRIBUTING.md file](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md)? Other than that [you can check our Discord Server for support](https://discord.gg/nestjs)

**Pull request closed without merging**
