### PR TITLE
Map key should not be object

### PR DESCRIPTION
**Pull request by hicdre**
```
const m = new Map();
m.set({a:1}, 2);
m.get({a:1}); // we get undefined
```

### CODE REVIEW

**Comment by Rafal2228** [comment]
Object is a valid map key. Your example isn't working because you're creating two different objects. Try something like this:
`
const key = {a: 1};
const m = new Map();
m.set(key, 2);
m.get(key);
`

**Comment by hicdre** [comment]
But when you use SocketContainer.getServer, you can not get the previous instance

**Comment by Rafal2228** [comment]
Just realized what `getServer` and `addServer` were actually doing. You're right, current behavior will return always create new instance of the server :)

**Comment by kamilmysliwiec** [comment]
Thanks @hicdre!! 🙂

**Pull request merged**
